### ISSUE TITLE
Character indent causes inaccurate selection

### ISSUE THREAD

**Issue by kennykaye** [Yggdroot/indentLine#104]
@Yggdroot Thanks for the great work on this plugin!  I have one small issue to report:

**The Issue:**
When plugin is enabled text selection is offset by number of indentations. Also when in visual mode, indentations disappear, revealing offset.

![screen shot 2015-01-20 at 12 31 42 am](https://cloud.githubusercontent.com/assets/3267574/5814088/4d5eda48-a03c-11e4-984c-b21042a939d1.png)
![screen shot 2015-01-20 at 12 31 50 am](https://cloud.githubusercontent.com/assets/3267574/5814089/4d744b94-a03c-11e4-874f-641a91d66124.png)

**Vim version:** 7.4.488

**Config:**
```vim
let g:indentLine_bufNameExclude = ['_.*', 'NERD_tree.*', '.*\.txt']
let g:indentLine_color_term = 239
let g:indentLine_char = '︙'
let g:indentLine_first_char = '︙'
let g:indentLine_showFirstIndentLevel = 1
set expandtab
set tabstop=2
set shiftwidth=2
```

Let me know if I can provide any more info!

**Comment by Yggdroot** [comment]
It's caused by the character '︙', you can choose another.

**Comment by sebastiant** [comment]
I also had this problem. Would you mind explaining the actual cause? Using utf-8 encoding i would have expected a utf-8 character to work fine as indent char
