### ISSUE TITLE
Invalid expression: &background is# "light"

### ISSUE THREAD

**Issue by wizicer** [Yggdroot/indentLine#107]
when I combined using with VimWiki, I'll get this error when I enter a wiki(defined by VimWiki) page

```
1 line less; before #1  1 seconds ago
"C:\xxx\xx\xx\index.wiki" [unix] 52L, 970C
Error detected while processing function <SNR>48_InitColor:
line    6:
E15: Invalid expression: &background is# "light"
line   16:
E15: Invalid expression: &background is# "light"
line   25:
E121: Undefined variable: term_color
E15: Invalid expression: "highlight Conceal ctermfg=" . term_color . " ctermbg=NONE"
line   26:
E121: Undefined variable: gui_color
E15: Invalid expression: "highlight Conceal guifg=" . gui_color .  " guibg=NONE"
line   28:
E15: Invalid expression: &term is# "linux"
line    6:
E15: Invalid expression: &background is# "light"
line   16:
E15: Invalid expression: &background is# "light"
line   25:
E121: Undefined variable: term_color
E15: Invalid expression: "highlight Conceal ctermfg=" . term_color . " ctermbg=NONE"
line   26:
E121: Undefined variable: gui_color
E15: Invalid expression: "highlight Conceal guifg=" . gui_color .  " guibg=NONE"
line   28:
E15: Invalid expression: &term is# "linux"
Error detected while processing function <SNR>48_Setup:
line   23:
E15: Invalid expression: &filetype is# ""
```

I'm not familiar with vim script, so I don't know why conditional statement can be "{something} is# {something}", I didn't see such grammar in help documentation, so I don't know why and how to fix it. So could you please help?

**Comment by Yggdroot** [comment]
I don't know VimWiki, is it a plugin? If yes, I guess it's a bug of it. 
you can try `:echo &background is# "light"` to see the output, it's a valid expression.

**Comment by wizicer** [comment]
thanks for your quick response, [VimWiki] is a handy tool, however, it is lack of maintenance for a while.

I tried that statement both in normal vim environment and [VimWiki] environment, it returns `0` in normal environment, but returns `dark` and follows a error message
```
E121: Undefined variable: is#
E15: Invalid expression: is# "light"
```

I guess, the environment is polluted by [VimWiki] with some special/system variables. However, I tried to understand the conditional statement, `is#` is a defined variable? Is there any reference to this type of grammer?

[VimWiki]: https://github.com/vimwiki/vimwiki

**Comment by Yggdroot** [comment]
`:h is#` to get the help.

**Comment by wizicer** [comment]
thanks a lot, finally, I gave up, as I need vimwiki which is lack of maintenance, I need to disable your plugin temporary, anyway, thanks for your great plugin.

-----
BTW, I tried following command:
```
:echo &background is#
```

in normal environment, I get this:
```
E121: Undefined variable:
E15: Invalid expression: &background is#
```

In VimWiki environment, I get this:
```
dark
E121: Undefined variable: is#
E15: Invalid expression: is# "light"
```
I still did not know what is changed by VimWiki.

**Comment by Yggdroot** [comment]
I think the issue can be fixed if you change `is#` to `==#`, you can have a try.

**Comment by wizicer** [comment]
sorry for late response because heavy work. I tried your suggestion, and it works like a charm, not only no error any more, I also can get the indent line in VimWiki. thanks

**Comment by Yggdroot** [comment]
Since it helped, I'll change the code like that.

**Comment by wizicer** [comment]
thanks for this change, I updated to your latest code. I will try and let you know if any new issue related to this new implementation mechanism.
