### ISSUE TITLE
Conceal highlighting group bg not transparent

### ISSUE THREAD

**Issue by kennykaye** [Yggdroot/indentLine#108]
In some situations the `Conceal` highlighting group is not overridden by other highlighting groups. In this case I believe it is `CursorLineNr`.

This certainly isn't a critical issue, but would be a nice to fix if there was one readily available.

![screen shot 2015-02-03 at 12 45 36 am](https://cloud.githubusercontent.com/assets/3267574/6016994/08e9e256-ab3e-11e4-9456-4a22d0178cc4.png)

**Comment by Yggdroot** [comment]
This is an issue of vim and can not be fixed by the plugin. 
you can add `let g:indentLine_noConcealCursor = 1` into your vimrc as a workaround.
