### ISSUE TITLE
No indent line after a set filetype

### ISSUE THREAD

**Issue by Freyskeyd** [Yggdroot/indentLine#113]
Hey,

I'm using a template `blade.php`, it's basicly html so sometimes i just execute:

`:set filetype=html` or `:set filetype=php`.

After define it, i can't see any line.

**Comment by Yggdroot** [comment]
You can add `autocmd FileType * IndentLinesReset` in your vimrc as a workaround.

**Comment by Freyskeyd** [comment]
ok thx
