### ISSUE TITLE
Lines only appear after forcing command "IndentLinesReset"

### ISSUE THREAD

**Issue by myriasofo** [Yggdroot/indentLine#114]
When I first open up my vimrc, the indent lines are visible. But whenever I source the vimrc, the lines disappear. I've made my vimrc file totally blank except to isolate the following:

    execute pathogen#infect()
    syntax enable

It seems to be `syntax enable` that causes the lines to disappear. Neither `IndentLinesToggle` or `IndentLinesEnable` do anything, *however*, `IndentLinesReset` causes the lines to come back! (But then, sourcing again removes the lines. I've been forced to put this reset command in my vimrc, but at every start, vim complains that it's not a recognized editor command.)

By the way, I removed all other packages except for indentLine. I'm using vim version 7.4. I've tried on both a clean install of Linux Mint, as well as Windows 7. I'm new to vim - is there something I'm missing?

**Comment by Yggdroot** [comment]
This issue can not be fixed by the plugin, the workaround can be:

    if !exists("g:syntax_on")
        syntax enable
    endif

**Comment by iv597** [comment]
In a similar realm, opening a new file with `:bufdo edit blah.js` will open the file without indent lines. I have to run `IndentLinesReset` to get them to come back.

@Yggdroot Your workaround did not fix the issue for me. vim 7.4.826 on OSX 10.10.

**Comment by Ikornaselur** [comment]
@iv597 Did you find a solution to this issue? The workaround didn't solve this for me either. Vim 7.4 and OSX 10.11 here.

**Comment by rafi** [comment]
Experiencing the same behavior as @Ikornaselur

**Comment by Yggdroot** [comment]
@Ikornaselur Because the `'syntax on'` or `'syntax enable'` will clear the syntax. if you have these two commands in your vimrc, the 'syntax' will be cleared after sourcing the vimrc. The work around in vimrc can be:

    if !exists("g:syntax_on")
        syntax enable
    endif
   or 

    if !exists("g:syntax_on")
        syntax on
    endif

**Comment by Yggdroot** [comment]
Some colorschemes may remove all existing highlighting at the very beginning. So `'colorscheme xxx'` should also be enclosed by `'if !exists("g:syntax_on")'`if necessary.
For instance,

    if !exists("g:syntax_on")
        syntax enable
        colorscheme xxx
    endif

**Comment by Ikornaselur** [comment]
Hm, that's a good point. I had seen `syntax` and `colorscheme` being wrapped in these if checks before, but didn't really think about it.

But sadly, it doesn't solve my issue. The issue remains the same even if I comment out both those lines.

**Comment by Yggdroot** [comment]
#114 #124 #129 #144 may be the same reason.

**Comment by wsdjeg** [comment]
@Yggdroot this does not fix this issue,I need running IndentLinesToggle twice to make the indentline works .I have no  syntax enable or syntax enbale or colorscheme xxx in my vimrc,BTW I am using dein.vim
