### ISSUE TITLE
Slows incredibly down in some files (tabs as possible reason)

### ISSUE THREAD

**Issue by ceraph** [Yggdroot/indentLine#115]
I'm currently working with files that have about 50 lines and in each line about 50 float values that are separated by a tab.
When I open one of those, everything in that buffer gets unbearably slow.

**Comment by Yggdroot** [comment]
Performance issue is known issue, such as #58, maybe you can set `'let g:indentLine_faster = 1' ` in your vimrc to have a try.

**Comment by ceraph** [comment]
That did the trick. Thanks!
