### ISSUE TITLE
can't see the indentLine and IndentLinesEnable don't work

### ISSUE THREAD

**Issue by nianiaJR** [Yggdroot/indentLine#116]
I use vundle install this plugin but it doesn't work, thx.

**Comment by ZhengRui** [comment]
I have the same problem, have you solved it?

**Comment by nianiaJR** [comment]
no，I'm in the mac terminal vi,  the version is 7.3. How about you?

**Comment by ZhengRui** [comment]
i am also in mac terminal, after installation through vundle, the IndentLinesEnable command could not even be found in Vi, so i gave up

**Comment by nianiaJR** [comment]
oh, we really have the same problem.Maybe it exist some trick in Mac vim. But the plugin in the vi of my fellow's mac work well.His version is 7.4.

**Comment by nianiaJR** [comment]
Ah~, I have found the reason. You can command : echo has('conceal') in your vim, if it return 0. That's why you can't see the indent line. If so you can brew a new version vim which support conceal or patch this feature.

**Comment by ZhengRui** [comment]
Yeah, you right, i `brew install vim` and then create a symlink to it, the vim shipped with osx does not has conceal compiled, but the vim installed through brew has conceal compiled.
