### ISSUE TITLE
it doesn't work in my term, but work fine in macVim

### ISSUE THREAD

**Issue by kdepp** [Yggdroot/indentLine#12]
I'm a mac user with vim 7.3. can't figure out why it doesn't work in the terminal

**Comment by KaoruDev** [comment]
I'm on 7.4 and it doesn't work. I'm used homebrew to install vim and am using it with iterm2

**Comment by codeninja-ru** [comment]
yep. it doesn't work on mac

vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 25 2015 18:27:50)
MacOS X (unix) version
Included patches: 1-979
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
