### ISSUE TITLE
No indent lines for the same buffer opened in another window

### ISSUE THREAD

**Issue by mrbiggfoot** [Yggdroot/indentLine#124]
The same buffer is opened in split windows. When I do "IndentLinesToggle", the indent lines only appear in the window with the least window number, no matter in what window the cursor is.

FWIW, I have "let g:indentLine_faster = 1" in my vimrc, but I doubt that it matters (have not checked).

**Comment by Yggdroot** [comment]
Can not reproduce.

**Comment by mrbiggfoot** [comment]
Here's a "main.cpp" file, which is not even correct, but is sufficient for a repro. 
```cpp

#include <stdio.h>

int main(int, char **)
{
  if (num_bytes > diff_bytes) {
        printf("HERE\n");
        num_bytes = diff_bytes;
        printf("num_bytes %d %x\n", num_bytes, num_bytes);
  }
  return 0;
}
```
The repro itself is:

$ vim main.cpp
\:vs
\:IndentLinesToggle

After that the indent lines are visible only in the left window, not the right. Reproducible in 100% cases on my setup. Maybe there's an interference with some other plugin... Please let me know how the repro goes.

**Comment by Yggdroot** [comment]
Can you show me your vimrc? I still can not reproduce.

**Comment by mrbiggfoot** [comment]
Sure. It's on github:
https://github.com/mrbiggfoot/vimp/blob/master/vimrc
