### ISSUE TITLE
No indent lines when reopen the file

### ISSUE THREAD

**Issue by guillaumewuip** [Yggdroot/indentLine#129]
I use nerdTree (which start when vim start). I usually do something like :

1. `vim`
2. open file A via nerdTree (indentLine presents because of `let g:indentLine_enabled = 1`)
3. do stuff
4. close file
5. do stuff on another file
6. reopen A via nerdTree

At point `6`, I always had to to refresh file with `:e` to see the lines (first strange thing) since I use indentLine ([commit bdad4e2ee6b1eccbfad0d12ddad46c9dca72d668](https://github.com/Yggdroot/indentLine/commit/bdad4e2ee6b1eccbfad0d12ddad46c9dca72d668)).
Today, I updated indentLine. And `:e` doesn't help anymore, nor `IndentLineEnable`, nor `IndentLineToggle`, nor `IndentLineReset`. I have to close and reopen vim (second strange thing).

Any ideas ?

(Oh, and [here's my `.vimrc`](https://github.com/guillaumewuip/Home/blob/master/.vimrc))

Thanks :)

**Comment by Yggdroot** [comment]
Can not reproduce.

**Comment by guillaumewuip** [comment]
Did you need more details ? How can I help you ?

**Comment by guillaumewuip** [comment]
Fixed.
I had `set hid ` in my `.vimrc` (hide a abandoned buffer).

**Comment by wsdjeg** [comment]
you should provide a mini vimrc,also report you os and vim version.otherwise no one can help you !

**Comment by sittim** [comment]
I am getting the same issue with Neovim on Ubuntu 15.04.  When the second window with the same file is opened, it there is no guides.  The only configuration I have in my rc file is:

`let g:indentLine_enabled = 1`

![selection_080](https://cloud.githubusercontent.com/assets/8825037/12680299/134c66ce-c677-11e5-9b76-c188c308d950.png)

Love this plugin, it is much less intrusive then the vim-indent-guides plugin, but this is the only caveat.

**Comment by rgrinberg** [comment]
I can confirm @sittim 's experience with neovim.

**Comment by wsdjeg** [comment]
can not reproduce ,I also use neovim 
![2016-02-04 22-35-59](https://cloud.githubusercontent.com/assets/13142418/12817956/aed3d696-cb8f-11e5-8ef0-baf7ca82b9a1.png)

**Comment by sittim** [comment]
It does not happen all the time, I tried to figure out how to reproduce it, but all I know is it happens sometimes.  A pretty sure way of doing it is to reload the .vimrc file, then the guides stop showing up for me.

**Comment by rgrinberg** [comment]
Perhaps it's a conflict with another plugin? @sittim can I see your vimrc?

**Comment by sittim** [comment]
Of course,

https://github.com/sittim/configs/blob/master/.config/nvim/init.vim

**Comment by wsdjeg** [comment]
re source vimrc ,the identline will gone in both two file,same as both vim and neovim
