### ISSUE TITLE
g:indentLine_char with 3 dots causing indent issues

### ISSUE THREAD

**Issue by naumazeredo** [Yggdroot/indentLine#131]
Using:
```
let g:indentLine_char = '︙'
```

Causes indent issues after some tabs:

![vim_indentline_issue](https://cloud.githubusercontent.com/assets/3757082/9658281/afc1b86a-521e-11e5-9670-b4275c66e974.png)

The cursor should blink after the whitespaces (insert mode), but after 2 extended tabs the cursor blinks at the last whitespace. When I write, the character is printed at the end of the line (which is correct), so the problem is only visual. The problem gets worse the more tabs you do:

![vim_indentline_issue_2](https://cloud.githubusercontent.com/assets/3757082/9658277/aaa33fd4-521e-11e5-98bb-f78586812a1e.png)
(Cursor at the end of the line. Going right would cause a wrap to the next line)

This issues only happens with this character from the ones listed on indentLine's readme.
The default character ```|``` or the other ones listed ``¦``, ```┆```, ```│``` works fine.

**Comment by moopie** [comment]
This is caused by `︙` being a fullwith character, i.e. it takes more space than regular characters
https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

This issue is the same as #119

**Comment by pallxk** [comment]
I came across this problem as well...

Is there any way to make fullwidth characters usable and useful as indent char?

Or what about removing fullwidth characters in readme, and documenting this?

**Comment by Yggdroot** [comment]
@pallxk removed from readme.

**Comment by pallxk** [comment]
@Yggdroot thanks, :+1:
