### ISSUE TITLE
Indentline Commands not showing up

### ISSUE THREAD

**Issue by jdblack** [Yggdroot/indentLine#135]
I have installed IndentLine via  vundle  on vim 7.3 on a new to me mac with a vimrc that has worked on linux for years.  Other plugins ( vundle, syntastic, vim-json, vim-json-bundle) are working fine, but indentline is not working.

I'm able to view help for indentline with  :help IndentLine  ,  but the actual indentline commands, like "IndentLineToggle" are not showing up as valid commands.

 

I'm alb

**Comment by Yggdroot** [comment]
Refer to issue #134, maybe it's the same case.
