### ISSUE TITLE
indentLine_faster breaks on files with multiple filetypes

### ISSUE THREAD

**Issue by JCavallo** [Yggdroot/indentLine#136]
Hi,

I used indentLine_faster for a while, and it caused a weird problem. I use a plugin which "completes" the python syntax for files matching a specific framework.

With indentLine_faster on, loading the file the first time would cause indentLines to appear properly, but some of the syntax was lost (specifically, everything that relied on matching "^" / start of line).

Forcing the syntax manually after that would restore the full syntax, but lose the indent lines.

I finally found out it was indentLines_faster that caused the problem. I just wanted to let you know.

**Comment by Yggdroot** [comment]
Yes, I know the issue, that is why `indentLine_faster` is not enabled default.
