### ISSUE TITLE
"breakindent" option leads to horizontal discontinuity of indentLines

### ISSUE THREAD

**Issue by dNItro** [Yggdroot/indentLine#141]
After using breakindent option ( `:set breakindent` ) to achieve smart wrap in vim i expect to see indentLines as normal i.e. preserving horizontal continuity BUT there is a discontinuity in indentLines beside wrapped lines of codes:
Normal
```html
<body>
    <div>
   | 	<p>
   | 	|	Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Nesciunt enim, officiis! Tempora, 
alias, debitis. Quae sint iste quidem, doloribus ad.
   |  	</p>
    </div>
</body>
```
`:set breakindent`
```html
<body>
    <div>
   | 	<p>
   | 	|	Lorem ipsum dolor sit amet, consectetur 
            adipisicing elit. Nesciunt enim, officiis! 
            Tempora, alias, debitis. Quae sint iste 
            quidem, doloribus ad.
   |  	</p>
    </div>
</body>
```
shouldn't it be like the following ?!
```html
<body>
    <div>
   | 	<p>
   | 	|	Lorem ipsum dolor sit amet, consectetur 
   |    |   adipisicing elit. Nesciunt enim, officiis! 
   |    |   Tempora, alias, debitis. Quae sint iste 
   |    |   quidem, doloribus ad.
   |  	</p>
    </div>
</body>
```

**Comment by Yggdroot** [comment]
Can not be fixed.

**Comment by maximoab** [comment]
Maybe too later but...

set breakindent
set breakindentopt=shift:2,min:40,sbr
set showbreak=\ \ \▏\ \▏\ \▏

adjust the shift:2 and the ultimate line according your spaces in indentation.
tnkz to this post https://stackoverflow.com/questions/1204149/smart-wrap-in-vim
