### ISSUE TITLE
Leading spaces breaks jade syntax highlighting

### ISSUE THREAD

**Issue by smarquez1** [Yggdroot/indentLine#143]
Enabling leading spaces as points break the jade syntax.
Whats the recommended way to change IndentLines configuration for this kind of file?

Relevant settings:

```
let g:indentLine_enabled=0
let g:indentLine_leadingSpaceEnabled=1
```

**Comment by larrybotha** [comment]
Setting indentation to tabs for jade files works for now.

**Comment by chellberg** [comment]
I'm having the same issue with leading spaces breaking Haml syntax highlighting.

**Comment by Yggdroot** [comment]
Update the plugin and have a try, this issue should be fixed.

**Comment by smarquez1** [comment]
@Yggdroot works fine. Close the issue when you are ready. Thanks!
