### ISSUE TITLE
Indent lines disappearing when using :Sex or :Vex

### ISSUE THREAD

**Issue by mrzool** [Yggdroot/indentLine#146]
Every time I use :Sex or :Vex the indent lines disappear in the original buffer.

Running the latest Vim in the terminal on Mac OS X.

Any idea?

**Comment by drgarcia1986** [comment]
same here :sob:

**Comment by sahibalejandro** [comment]
I having this issue too, when I open vinegar (netrw) and then close, indent lines disappear, then I need close all buffers and reopen or call :IndentLinesToggle twice.

**Comment by ZeroKnight** [comment]
I notice this issue as well if I call `:e` to reload a buffer.

**Comment by Yggdroot** [comment]
@ZeroKnight Please use the latest version.

**Comment by Yggdroot** [comment]
Removing `filetype detect` in `$VIMRUNTIME/autoload/netrw.vim` will solve this issue.
