### ISSUE TITLE
Cannot get it to work on Mac

### ISSUE THREAD

**Issue by harmor11** [Yggdroot/indentLine#151]
I have vim 7.3 and meet all the requirements, but the vertical lines don't show up.

.vimrc:
`execute pathogen#infect()`
 `syntax on`
 `set nu`
 `set tabstop=4`
 `set ruler`
 `set bg=dark`
 `set showcmd`
 `set expandtab`
 `set autoindent`
 `set colorcolumn=80`
 `let g:indentLine_char = '|'`

**Comment by symbiat** [comment]
Same here - setting up a new Mac. In my case `:IndentLinesToggle` produces an error: `Not an editor command`.

**Comment by Yggdroot** [comment]
Refer to issue #59, to see if it helps.

**Comment by harmor11** [comment]
Actually if you just upgrade to vim 7.4, it works magically.

**Comment by cdated** [comment]
Agreed works for me on Mac with version 7.4.1054
