### ISSUE TITLE
pangloss vim-javascript plugin imcompability

### ISSUE THREAD

**Issue by cjnucette** [Yggdroot/indentLine#154]
Hi, when i enable the plugin this happens

![screenshot from 2016-04-22 15-43-20](https://cloud.githubusercontent.com/assets/2278326/14753741/0ce6068e-08a1-11e6-9c5f-6566fa610a94.png)

This only happens with inline javascript in html file.

my .vimrc:
" indentLine
let g:indentLine_enable=1
let g:indentLine_fileType=['javascript', 'html', 'css', 'scss', 'typescript']
let g:indentLine_color_term=239
let g:indentLine_color_gui='#A4E57E'
let g:indentLine_char='┊'

**Comment by xaviervalarino** [comment]
I am also using [pangloss-javascript plugin](https://github.com/pangloss/vim-javascript) and have been experiencing this issue.
![js-no-show-indent](https://cloud.githubusercontent.com/assets/4262486/14769961/93827438-0a19-11e6-9670-0a63658fb741.png)

**Comment by Yggdroot** [comment]
@cjnucette Does those lines' indentation is using tabs?
@xaviervalarino because default value of ·g:indentLine_indentLevel· is 10. You can set it to 20.

**Comment by xaviervalarino** [comment]
@Yggdroot Thanks! this solved the issue. Is there any way to get this plugin to detect a files indent settings like [detectIndent](https://github.com/ciaranm/detectindent)?

**Comment by cjnucette** [comment]
@Yggdroot No, white spaces.

This are the relevant lines in my .vimrc:

" Use spaces instead of tabs
set expandtab

" Be smart when using tabs ;)
set smarttab

" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=4

" Linebreak on 500 characters
set lbr
set tw=500

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

**Comment by cjnucette** [comment]
Sorry closed by error

**Comment by Yggdroot** [comment]
Could you show me the sample file with text but not picture?

**Comment by cjnucette** [comment]
Sure:
    
    <script>
        System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                }
            }
        });
        System.import('app/main')
            .then(null, console.error.bind(console));
    </script>

**Comment by Yggdroot** [comment]
This is a conflict with vim-javascript plugin. Can only be solved by vim-javascript plugin.

**Comment by sassanh** [comment]
@Yggdroot What's the conflict?

**Comment by jalcine** [comment]
Yeah, that message was a bit cryptic. How is this an issue on the `vim-javascript` side?
