### ISSUE TITLE
How do you change the character for the leading space?

### ISSUE THREAD

**Issue by NullVoxPopuli** [Yggdroot/indentLine#161]
![image](https://cloud.githubusercontent.com/assets/199018/17746410/ef084e5e-647d-11e6-89ba-18d3fd338310.png)

Currently, spaces are little carets. I'd like them to be unicode centered dots

**Comment by Vladar4** [comment]
```
set listchars=tab:·\ ,trail:·
```
in the .vimrc

**Comment by NullVoxPopuli** [comment]
![image](https://cloud.githubusercontent.com/assets/199018/17752601/98a8931c-649a-11e6-81c6-9c9cae1ddd34.png)

it didn't work?

**Comment by NullVoxPopuli** [comment]
(I'm new to vim)

**Comment by Vladar4** [comment]
try adding ```set list``` command afterwards.

**Comment by NullVoxPopuli** [comment]
![image](https://cloud.githubusercontent.com/assets/199018/17752771/572c272c-649b-11e6-8fcb-a92857598e41.png)

**Comment by Vladar4** [comment]
[More info](http://vim.wikia.com/wiki/Highlight_unwanted_spaces#Using_the_list_and_listchars_options)

**Comment by NullVoxPopuli** [comment]
Just found this: http://stackoverflow.com/a/19233453/356849

> _The list+listchars combo can show trailing spaces but not leading spaces._

**Comment by Yggdroot** [comment]
`let g:indentLine_leadingSpaceChar = 'character you want'`

**Comment by NullVoxPopuli** [comment]
thanks! I couldn't find that on the readme.
