### ISSUE TITLE
Don't display correctly with some config files (for eg. json) 

### ISSUE THREAD

**Issue by lxynox** [Yggdroot/indentLine#163]
For some reason, this plugin cuts off(hides) double quotes `""` in json files. The char is actually there yet hidden by this plugin.

My package.json looks like this (with upper window enabled LeadingSpace)
<img width="468" alt="screen shot 2016-08-21 at 5 34 09 pm" src="https://cloud.githubusercontent.com/assets/10333817/17839912/8aa3dbd6-67c5-11e6-8d25-c0e7d961c8ea.png">

Any ideas or solutions?

**Comment by Misfit-John** [comment]
https://github.com/Yggdroot/indentLine/issues/140
This is one feature from conceal's built-in json.vim. You can refer to this issue to see more details.

**Comment by mattolenik** [comment]
None of those fixes work in neovim, and I suspect regular vim as well. They used to but no longer do.

**Comment by Yggdroot** [comment]
Duplicate with issue #140 .
