### ISSUE TITLE
:IndentLinesToggle not working

### ISSUE THREAD

**Issue by drzel** [Yggdroot/indentLine#169]
`:IndentLinesToggle` seems to disable and then immediately enable the guides on Vim 8.

`let g:indentLine_enabled = 0` seems to workaround the problem though.

**Comment by ikogan** [comment]
Confirming this behavior in vim 7.4. If I do `:IndentLinesToggle` or `:IndentLinesDisable`, they will re-enable again as soon as I try to select text to copy (while holding out to not send the clicks to the underlying application) in ITerm.

`let g:indentLine_enabled = 0` prior to `:IndentLinesToggle` seems to fix it.
