### ISSUE TITLE
IndentLine will disable quotes in Json file

### ISSUE THREAD

**Issue by linrongbin16** [Yggdroot/indentLine#172]
please tell me how to disable this feature.

**Comment by zhaochenyou** [comment]
ok, I find it, this feature really cost me lots of time to find it out...

**Comment by danielim** [comment]
could you post your solution for future reference?

**Comment by luisdavim** [comment]
let g:vim_json_syntax_conceal = 0 should do the trick.

**Comment by danielim** [comment]
```
(...)
" I use Vundle to install plugins.
Plugin 'Yggdroot/indentLine'
(...)
let g:indentLine_enabled = 1
let g:vim_json_syntax_conceal = 0
(...)
```
and when opening my package.json, it still conceals quotation marks.

I attached my complete .vimrc file
[.vimrc file](https://github.com/Yggdroot/indentLine/files/584884/new.2.txt)

**Comment by zhaochenyou** [comment]
Thanks for share.
Before this, I just disable indentLine for *.json file:
`autocmd Filetype json let g:indentLine_setConceal = 0`

**Comment by petervaro** [comment]
@luisdavim worth mentioning, your solution is only working with the `vim-json` plugin! (But it is working with it pretty well :) )

**Comment by akkartik** [comment]
@Yggdroot: I'm curious why `indentLine_setConceal` exists. Turning it on seems to disable indentlines. Is there ever a situation where this plugin is useful with `indentLine_setConceal` turned on? I'm planning to just add this to my vimrc:

```
autocmd Filetype json let g:indentLine_enabled = 0
```

Thanks!

/cc @zhaochenyou @petervaro

**Comment by shengkui** [comment]
Meet this issue too, and disable the plugin for json file now

**Comment by Yggdroot** [comment]
Duplicate with issue #140 .

**Comment by solomonxie** [comment]
It appears and annoys me a lot that I can type a valid JSON string which everything I typed in JSON file will be changed or deleted.
I took like half hour to debug in my vimrc to find out the plugin `indentLine` is the one messing up with it.

Thanks to @akkartik, only this one works for me:
```vim
autocmd Filetype json let g:indentLine_enabled = 0
```

**Comment by sergioatvandebron** [comment]
Only one that works for me is

```vim
autocmd Filetype json :IndentLinesDisable
```

**Comment by LvChengbin** [comment]
> let g:vim_json_syntax_conceal = 0 should do the trick.

This doesn't work for me.

**Comment by mversic** [comment]
yes, this issue shouldn't be closed, `let g:vim_json_syntax_conceal = 0` still doesn't work

**Comment by avahe-kellenberger** [comment]
Any updates on this bug?

**Comment by lethargosapatheia** [comment]
I think the plugin is very useful and great. Unfortunately because it hides the quotes in json, I simply cannot afford to use. Are there any plans to fix this? None of the proposed solutions worked for me.

**Comment by lethargosapatheia** [comment]
> FWIW - adding this to my `.vimrc` fixed this issue for me:
> 
> ```
> autocmd Filetype json let g:indentLine_setConceal = 0
> ```
> 
> (source: https://stackoverflow.com/a/63502835)

Funny. This disabled the plugin completely.

I think the plugin is great and I like it a lot, it's also relatively flexible. Unfortunately the fact that it hides the quotes (really bad idea!) in json makes it simply unusable. Are there any plans to fix things?
