### ISSUE TITLE
No indent lines after 10 levels of indentation

### ISSUE THREAD

**Issue by BreadPaPa** [Yggdroot/indentLine#176]
Using Macvim with Vim 8.0. Everything works as expected except that when indentation level is over 10 the indent lines disappeared, as shown in attached pic. What could be the issue or is there any config that I'm missing? Thanks.

![screen shot 2016-11-09 at 10 52 24 am](https://cloud.githubusercontent.com/assets/621540/20146922/6ee4f4e0-a66b-11e6-939f-360e300a8f80.png)

**Comment by Yggdroot** [comment]
·let g:indentLine_indentLevel = 100·
