### ISSUE TITLE
Show current indentation "header" in status line

### ISSUE THREAD

**Issue by pryg-skok** [Yggdroot/indentLine#178]
Hi,

is it possible to show current indentation level in status line or somewhere else? By header I mean first line of fold. For example:
```
for i in items:
    process_item(i)    
    print i

"Header": "for i in items:"
```

```
def hello_world():
    print "hello world"
    return

"Header": "def hello_world():"
```

How it can be achieved? 
It would be helpful when navigating deep down through large blocks of nested code -- every time I can see where am I, which function, loop, or other block.

**Comment by Yggdroot** [comment]
It's not the business of this plugin.
