### ISSUE TITLE
Leading spaces sometimes shown with g:indentLine_enabled = 0

### ISSUE THREAD

**Issue by jransijn** [Yggdroot/indentLine#179]
For example, when alt-tabbing or resizing the terminal, the leading spaces appear, even with `indentLine_enabled = 0`. Pretty sure this is caused by indentLine, as LeadingSpacesDisable removes the leading spaces again.

**Comment by Yggdroot** [comment]
It is `g:indentLine_leadingSpaceEnabled`  not `indentLine_enabled` that can control the leading spaces.

**Comment by YoYoYonnY** [comment]
But isn't `g:indentLine_enabled = 0` supposed to disable the plugin completely? As of right now, I'm having to disable it in Vundle.

**Comment by Yggdroot** [comment]
If you want to disable the plugin, use `let g:indentLine_loaded = 1` instead.

**Comment by YoYoYonnY** [comment]
So the readme is wrong, then? (See pull request)

**Comment by Yggdroot** [comment]
Readme is not wrong. `let g:indentLine_loaded = 1` is do not use the plugin. `let g:indentLine_enabled = 0` is do not show the line by default.

**Comment by YoYoYonnY** [comment]
We might be talking about the same problem as at #193 here.

`README` might not be wrong, but it is confusing at best (See pull request)

I'm not sure if there's a way to stop indentLine from showing leading spaces after resizing etc. besides forcefully disabling it, but the current behaviour is definitely unexpected, and this severely limits the usability of `g:indentLine_enabled = 0`.
