### ISSUE TITLE
indentation chars showing within the line

### ISSUE THREAD

**Issue by albasili** [Yggdroot/indentLine#180]
I'm not quite convinced this is a desired behavior or something I should be able to configure (didn't find anything related in the doc though). Whenever I have lines with more than a tabstop worth of spaces in it I have the indentLine character showing up:

```
task automatic pulse(   |   |   |   // this is a comment
    input a;
    input b;
    begin: on
    |     start = a;
    |     .....
    end
endtask
```

I do not believe that the "|" character should be shown in the first line of this code since there's no indentantion of whatsoever, it is just spaces within some text.

How to fix it?

**Comment by Yggdroot** [comment]
Can not reproduce.

**Comment by albasili** [comment]
Indeed it is happening on systemverilog files where I can use line continuation without any escape char. so, being more specific the previous example would look like this:

```
task automatic pulse(   |   |   |   // this is a comment
    input a,   |   |   |   |   |   |   |   |  // here's another comment
    input b);                               // here yet another comment (no indentchar)
    begin: on
    |     start = a;
    |     .....
    end
endtask
```

I have another plugin to handle systemverilog files (https://github.com/WeiChungWu/vim-SystemVerilog) and I do not know if there's some sort of conflict with it.

Any hint is appreciated.

**Comment by Yggdroot** [comment]
I think there indeed is conflict.

**Comment by albasili** [comment]
I confirm, once I changed plugin to handle systemverilog files I stopped having this behavior.
