### ISSUE TITLE
First char linux

### ISSUE THREAD

**Issue by vgsantoniazzi** [Yggdroot/indentLine#185]
Hi guys,

Previously I saw an issue related with problem with first char shown in linux: 

![selection_001](https://cloud.githubusercontent.com/assets/1229625/22449982/b27e69c8-e74a-11e6-8ec7-422a18bc3fa7.png)

I remember that there's a version which I can use, I made a download from raw.

My desktop died and my backup didn't work. I need this, for my sanity.

**Comment by Yggdroot** [comment]
Do you mean "let g:indentLine_showFirstIndentLevel = 1"?

**Comment by vgsantoniazzi** [comment]
It worked! Thank you!
