### ISSUE TITLE
levels of indentation displaying next to line numbers?

### ISSUE THREAD

**Issue by bloodstalker** [Yggdroot/indentLine#187]
how can I have levels of indentation displaying next to line number like in the screenshots?

**Comment by Yggdroot** [comment]
`let g:indentLine_showFirstIndentLevel = 1`

**Comment by bloodstalker** [comment]
i put that into my vimrc but its still not showing anything. are there any requirements for this option to work?
Also I'm using kshenoy/vim-signature. could this interfere with indentLine?

**Comment by bloodstalker** [comment]
well i did try turning vim-signature off but nothing happened.

**Comment by bloodstalker** [comment]
is this a gvim only feature?

**Comment by Yggdroot** [comment]
No, I think there is a conflict with other plugin.

**Comment by bloodstalker** [comment]
ok thank you
