### ISSUE TITLE
IndentLine's characters do not reappear after using Sneak's label mode.

### ISSUE THREAD

**Issue by talw** [Yggdroot/indentLine#190]
Hi!

I'm using IndentLine and [Sneak](https://github.com/justinmk/vim-sneak) in my configuration.

If I use sneak's label mode, all the line characters disappear, and I can only restore them by doing things like executing :e or :IndentLinesToggle twice.

I assume this has to do with conceal? Seeing as how both IndentLine and Sneak use it.

 I've opened an [issue](https://github.com/justinmk/vim-sneak/issues/198) over on Sneak's issues page first and it was closed with the following comment:

> Yeah, seems like indentLine isn't getting re-enabled after temporarily disabling syntax. indentLine should listen to the Syntax autocmd. Other than that, not much can be done.

**Comment by Yggdroot** [comment]
Maybe this issue has been fixed now.

**Comment by talw** [comment]
Tested it after updating the plugin and it works perfectly!

Thanks!
