### ISSUE TITLE
vim 8.0 compatibility not good 

### ISSUE THREAD

**Issue by zhaogaolong** [Yggdroot/indentLine#192]
gvim 8.0  Display incomplete, can only display part

**Comment by pangteypiyush** [comment]
Indent lines are inconsistent and absent between many blocks of codes ( or indents). 
I will stick with indent-guides plugin.

**Comment by Yggdroot** [comment]
Can you describe in more detail?

**Comment by pangteypiyush** [comment]
As compared to indent-guides plugin, indent-line plugin does not respect my tabstop(and other related configs). See my vimrc : [link](https://raw.githubusercontent.com/pangteypiyush/dotfiles/master/vimrc)

Here tabstop and shiftwidth is set to 2, but indents starts at 8th.
![screenshot from 2017-05-04 11-33-00](https://cloud.githubusercontent.com/assets/9109260/25692056/823ffc38-30bd-11e7-8e99-67217af10fac.png)

**Comment by Yggdroot** [comment]
Because you have `set shiftwidth=8` in your vimrc, you should `set shiftwidth=2`.

**Comment by pangteypiyush** [comment]
@Yggdroot line #[225-226](https://github.com/pangteypiyush/dotfiles/blob/master/vimrc#L225) sets my tabstop and shiftwidth as per filetype, i.e 2.

**Comment by Yggdroot** [comment]
Fixed.

**Comment by zhaogaolong** [comment]
I know my config question, I am question. bucause html shiftwidth config different python config. 
indentLine plugin is very nice. thank you.
