### ISSUE TITLE
glitch on nerdtree

### ISSUE THREAD

**Issue by adelarsq** [Yggdroot/indentLine#196]
Last two commits broke nerdtree with [webdevicons](https://github.com/ryanoasis/vim-devicons
) plugin showing the [ and ] signals:

![image](https://cloud.githubusercontent.com/assets/430272/25413372/424bd44e-2a00-11e7-861f-a5204e884e54.png)

**Comment by Yggdroot** [comment]
Please set `let g:indentLine_fileTypeExclude = ['nerdtree']` in vimrc, to see if it helps.

**Comment by adelarsq** [comment]
I'm using:
```
let g:indentLine_fileTypeExclude = ['help', 'nerdtree', 'startify', 'tagbar', 'vimfiler', 'markdown', 'minimap']
```
After the last changes its working again 🤔 😄
