### ISSUE TITLE
Option `g:indentLine_fileTypeExclude` interferes with conceal

### ISSUE THREAD

**Issue by DerWeh** [Yggdroot/indentLine#197]
I have seat the options 

```
let g:indentLine_fileTypeExclude = ['help', 'text']
let g:indentLine_setConceal=0
```

If I open now a `text` or `help` file, the `conceallevel` will be set to 0 instead of keeping my settings. Removing `let g:indentLine_fileTypeExclude = ['help', 'text']` fixes this issue, my `conceallevel` will be kept.

**Comment by Yggdroot** [comment]
I reverted the last commit, please try again.

**Comment by DerWeh** [comment]
Fixed the problem, it's working properly again.
