### ISSUE TITLE
Since 2ceee22d25961dcc217eadbdffe6a4b043655d13 startify no longer ignored

### ISSUE THREAD

**Issue by Konfekt** [Yggdroot/indentLine#204]
Since commit 2ceee22d25961dcc217eadbdffe6a4b043655d13 , with 
```vim
let g:indentLine_faster = 1
let g:indentLine_concealcursor = ''
let g:indentLine_conceallevel = 1
let g:indentLine_fileTypeExclude = [ 'startify' ]
```
and `http://github.com/mhinz/vim-startify/`, IndentLine is no longer disabled after starting Vim when the `Startify` screen appears.

**Comment by Yggdroot** [comment]
Fixed.

**Comment by Konfekt** [comment]
Thanks!
