### ISSUE TITLE
Syntax highlighting issue where background is weird

### ISSUE THREAD

**Issue by benlieb** [Yggdroot/indentLine#205]
I just added the indentLine plugin, and I love it apart from this annoying syntax highlighting issue where the background of the dividing character stays black while the rest of the line is highlighted. It's really distracting for me. How can I fix this and make the background the same as the rest of the line, and the dividing character still visible?

http://stackoverflow.com/questions/44077281/syntax-highlighting-issue-in-vim-where-background-is-weird

**Comment by Yggdroot** [comment]
Duplicate with issue #125 .
