### ISSUE TITLE
Not working for google's go language when golang file is formatted by gofmt

### ISSUE THREAD

**Issue by haifenghuang** [Yggdroot/indentLine#208]
The indentLine is not working for google's go language.The golang file is formatted by gofmt command, so it contains TABs, and i tried to convert all TABs to spaces, it worked as expected.

**Comment by Yggdroot** [comment]
This plugin is used for displaying thin vertical lines at each indentation level for code indented with spaces. For code indented with tabs I think there is no need to support it, because you can use :set list lcs=tab:\|\ (here is a space).
