### ISSUE TITLE
Netrw preview

### ISSUE THREAD

**Issue by crivotz** [Yggdroot/indentLine#209]
Hi,
when I try to preview a file with netrw (`p` key on a file inside netrw, you must enable `netrw_preview`) I get the following error:

```
Error detected while processing function <SNR>89_IndentLinesDisable:
row 4:
E803: ID not found: 24
E803: ID not found: 25
E803: ID not found: 26
E803: ID not found: 27
E803: ID not found: 28

and more...
```

Any tips?

**Comment by Yggdroot** [comment]
Are you using the latest version?

**Comment by crivotz** [comment]
My fault, I was convinced to be on the latest version

Thanks
