### ISSUE TITLE
Seems IndentLine has conflicts with vim-go

### ISSUE THREAD

**Issue by eschao** [Yggdroot/indentLine#210]
I use **vim-go** to coding golang in Vim, but I can't see indent line when editing go file. I set the below options in my .vimrc:
```vim
set conceallevel=1
let g:indentLine_conceallevel=1
```
And I can make sure the ```shifttable```, ```tabstop``` and ```expandtab``` are correct. I can see indent line when I edit javascript file which is also use 2 space indent setting. But indent line doesn't work for go file. I suspect there is some conflicts with vim-go, Does anyone has the same problem?
BTW, I'm using Vim 8.0, the problem can be found both in Vim terminal and MacVim.

Any comment are really appreciated!

**Comment by eschao** [comment]
Ok, I got the reason, seems vim-go will reset my ```expandtab``` settings, I add the below line to reset it:
```vim
autocmd FileType go setlocal expandtab
```

**Comment by 0x5010** [comment]
Same issue,but can't fix.

**Comment by jinbeomhong** [comment]
@0x5010 You can enable indentLine by appending this line below in `.vimrc`:

```.vimrc
set list lcs=tab:\|\ (last character is a space...)
```

Basically, indentLine only works with space. but `go fmt` indents code with tabs only. [SO : Indentation in Go: tabs or spaces?](https://stackoverflow.com/a/19094725/9304999). So you can see indentLine works well when you indent go code with spaces.

And you can find this solution in [indentLine README in the first paragraph](https://github.com/Yggdroot/indentLine#indentline):

> This plugin is used for displaying thin vertical lines at each indentation level for code indented with spaces. **For code indented with tabs I think there is no need to support it, because you can use :set list lcs=tab:\|\ (here is a space)**.

**Comment by cybaol** [comment]
However, if I set list lcs=tab:\|\ (last character is a space...)
the  Indentline is too highlight.
I want the shadow line like plugin vim-indentline

**Comment by cybaol** [comment]
![Uploading 图片.png…]()

**Comment by cybaol** [comment]
![Uploading 图片.png…]()
I want like this

**Comment by codebysandwich** [comment]
@cybaol try :hi NonText guifg=#6E6761

**Comment by gitsang** [comment]
for vim

```
autocmd FileType go set list lcs=tab:\┊\ "(last character is a space...)
autocmd FileType go hi SpecialKey ctermfg=gray
```
