### ISSUE TITLE
[Question] An question of background color of indent line

### ISSUE THREAD

**Issue by jtr109** [Yggdroot/indentLine#212]
Hello, the plugin indentLine is great! Thanks a lot.

Now I meet a problem after updating. The indent line appears with grey background which I don't need. Is there any configurations should I setting to solve It?

By the way, both the cursorline and cursorcolumn I have set.

![image](https://user-images.githubusercontent.com/13946679/27000810-b3f006e6-4dec-11e7-9f13-68b380c9ce70.png)

**Comment by Yggdroot** [comment]
By default, there is no background. Maybe some other plugin changes the color, you can use:
`:verbose hi Conceal` to see the output.

**Comment by jtr109** [comment]
It may be changed by the theme molokai.vim. I will find some way to change it.

This issue can be closed. Thanks again!
