### ISSUE TITLE
My indentline char was attached to an underline.

### ISSUE THREAD

**Issue by authorcamus** [Yggdroot/indentLine#213]
I use the default settings without adding any comments.I'd like to know how to remove the underline.Thanks!
![image](https://user-images.githubusercontent.com/19421172/28000258-3add322e-6557-11e7-98c8-9b564a04ef45.png)

**Comment by Yggdroot** [comment]
Please update the plugin and have a try.

**Comment by authorcamus** [comment]
It worked. Thanks!
