### ISSUE TITLE
indentLine_color_gui fallback to medium grey ?

### ISSUE THREAD

**Issue by pabuisson** [Yggdroot/indentLine#216]
Hey guys,

I'm having an issue here, using neovim 0.2.0 and the `indentLine_color_gui` option. Here's what's happening : 

1. if I define a red colour, say `let g:indentLine_color_gui = '#D20000'`. Then it's working fine, I get what's expected, redish indent lines : 

<img width="80" alt="red" src="https://user-images.githubusercontent.com/769918/28660443-3628c900-72b3-11e7-9273-bd67ab7ba0c9.png">

2. If I define a "dark gray color" (which is saner than red for indentation marks 🙃), then there's a fallback to a medium grey, far from the expected colour. I can expect a slight change in the final output colour, but here, there's a huge difference. Say with `let g:indentLine_color_gui = '#111111'` (really dark gray),  I'm getting this, which is around a medium gray / `#777777`: 

<img width="110" alt="expected dark gray" src="https://user-images.githubusercontent.com/769918/28660518-87d396b8-72b3-11e7-852f-321e5be4681f.png">

Any ideas of what I'm missing here?

**Comment by Yggdroot** [comment]
Make sure you are using `gvim` or `gneovim`, if not, please use `g:indentLine_color_term`.
Otherwise, I think this is an issue of neovim.

**Comment by pabuisson** [comment]
Thanks for the answer. Since neovim is used with true color / termguicolors, it looks like it's picking up the `indentLine_color_gui` setting but not the `indentLine_color_term` at all. 

I guess I have a MacVim installation around here, I'll try to see if I reproduce the bug in it. I'll keep you posted.

**Comment by pabuisson** [comment]
Well indeed, it works well in MacVim. Maybe there are other neovim users around here than can tell me how it behaves on their own setup? Otherwise well, I guess this issue can be closed... even if I don't know how to solve the problem 😅
