### ISSUE TITLE
problem with char display

### ISSUE THREAD

**Issue by jdavid2** [Yggdroot/indentLine#217]
Hi
plugin is not able to display let g:indentLine_char = "|"  . I add in my .vimrc
set encoding=utf-8

![capture](https://user-images.githubusercontent.com/30869886/29208990-8a94434a-7e8c-11e7-81d3-fd1fd0762267.PNG)

thanks for your help

**Comment by Yggdroot** [comment]
Can not reproduce.

**Comment by jdavid2** [comment]
Hi

here is the solution
let g:indentLine_leadingSpaceChar = '.'
