### ISSUE TITLE
Not continue line

### ISSUE THREAD

**Issue by simepy** [Yggdroot/indentLine#219]
Hello,

I desire like this like Atom:
![image](https://user-images.githubusercontent.com/12037541/29837558-c2fd338e-8cf8-11e7-97e9-c4d7a6ce059d.png)

But i have this: 
![image](https://user-images.githubusercontent.com/12037541/29837203-d293d5ba-8cf7-11e7-809c-79650ef9d362.png)

What is the option for enable this function ?
I have NeoVim v0.2.0

Thanks in advance

**Comment by Yggdroot** [comment]
are you sure all the white spaces are spaces but not tab?

**Comment by simepy** [comment]
Thanks,
Is my bad, it was tabs, I just add "set expandtab" to convert tab in space and re-indent.
