### ISSUE TITLE
Jumping between tags removes indent line? Disappears? 

### ISSUE THREAD

**Issue by her** [Yggdroot/indentLine#220]
Hey thanks for the plugin. 

The problem I'm running into is: 

Open file (indentLine is there)
Jump to tag definition in another file (still have indentLine) 
Return to previous file (indentLine disappears)

I've tried `:IndentLinesEnable` and  `:redraw` but the indent lines will not reappear until I've closed the buffer/file completely and restarted vim. 

Wondering if you're able to reproduce this? I don't have any configurations set for indentLine just the Plug installed. 

Cheers guys, thanks again!

**Comment by Yggdroot** [comment]
Can not reproduce. Could you provide a minimal vimrc and the exact steps to reproduce?

**Comment by her** [comment]
Yeah, I'll get one up, and will repost with steps to repro. 

I'm noticing this same behavior when jumping between branches outside of a vim session requiring a `:edit!`.

**Comment by her** [comment]
hey @Yggdroot 

got some time to test this on your suggestion of a minimal vim. turns out this is what was causing this issue:

`au FileType * set cole=0`

I think this may have to do with how VIM will reevaluate conceallevel per buffer, but I'm curious maybe if you have any additional insight. 

I'm thrilled this was just a configuration issue on my part as your plugin is far and away the best indent guide I've had the pleasure of using. 

Thank you again so much for your hard work! 

Cheers 👍
