### ISSUE TITLE
IndentLine not working in Vim on MacOS

### ISSUE THREAD

**Issue by kvuong2711** [Yggdroot/indentLine#221]
I've installed the indentLine properly through Vundle, but :IndentLinesToggle doesn't work. I also put let g:indentLine_color_term = 239, let g:indentLine_char = '|', let g:indentLine_conceallevel = 1, but they don't work. I have MacOS 10.13, Vim 8.0.
Thanks.

**Comment by Yggdroot** [comment]
duplicated with issue #59 , #151 .
