### ISSUE TITLE
redraw all windows include preview may cause vim slow

### ISSUE THREAD

**Issue by meritozh** [Yggdroot/indentLine#222]
Talk is here https://github.com/Valloric/YouCompleteMe/issues/2780, the second last comment.

Can you provide one setting let `indentLine` won't redraw current window when ignore **preview** and **quickfix** window opened?

**Comment by meritozh** [comment]
And could it be async in vim 8?

**Comment by alex-shamshurin** [comment]
Try this https://github.com/alex-shamshurin/indentLine until https://github.com/Yggdroot/indentLine/pull/224 will be merged or improved.

**Comment by Yggdroot** [comment]
set `let g:indentLine_newVersion = 0` and have a try.

**Comment by meritozh** [comment]
@Yggdroot If set `let g:indentLine_newVersion = 0`, there is no indentation guide, if not set, still produce slow issue.

**Comment by Yggdroot** [comment]
I fix an issue just now, could you check if the fix also fixes your issue?

**Comment by meritozh** [comment]
No, also need call `indentLineReset` manually when enable `color_coded`.

**Comment by Yggdroot** [comment]
Remove `let g:indentLine_newVersion = 0` and have a try.
