### ISSUE TITLE
Only indent the first and last level

### ISSUE THREAD

**Issue by WorkerOfSecret** [Yggdroot/indentLine#223]
I am using vim ver 7.4 on Ubuntu 16.04 and just like the instruction I move all the after, glyph, doc to the .vim dir but it only indent the last level of my code at first and then first level after I set the indentLine_showFirstIndentLevel value from 0 to 1.

If my code have 5 level then it only show level 1 and 5, nothing is happen in level 2, 3, 4.
Someone pls tell me what to do to fix this problem

**Comment by Yggdroot** [comment]
Make sure they are spaces but not tabs.

**Comment by WorkerOfSecret** [comment]
I don't have any tabs in my code so I'm sure my code are completely space only and it still not work
/home/nguyen/ピクチャ/Screenshot from 2017-10-10 09-45-31.png

**Comment by Yggdroot** [comment]
```
echo &shiftwidth
echo &tabstop
```
What is the output of them?

**Comment by WorkerOfSecret** [comment]
I don't understand code so I was searching for the shiftwidth and tabstop, and I found them in line 115, 133, 199
![screenshot from 2017-10-10 11-01-48](https://user-images.githubusercontent.com/27545565/31366239-e738dc58-adaa-11e7-8526-7a413c8e4113.png)
![screenshot from 2017-10-10 10-57-52](https://user-images.githubusercontent.com/27545565/31366249-ec47eb1c-adaa-11e7-9250-f0d910c4bfc5.png)

**Comment by Yggdroot** [comment]
1. Enter vim
2. Type : 
3. Type `echo &shiftwidth`
4. Type `enter`
to see the output.

**Comment by WorkerOfSecret** [comment]
Oh it is 8

**Comment by Yggdroot** [comment]
You need set the value of shiftwidth to what you want, for example 4.
Add `set sw=4` in your vimrc.

**Comment by WorkerOfSecret** [comment]
Can u explain the set sw=4 for me pls. What will happen if I change the value of sw into 4 or 8 or 3 or any others number

**Comment by Yggdroot** [comment]
`:h shiftwidth`

**Comment by Yggdroot** [comment]
You can change the value and see the indent level.

**Comment by WorkerOfSecret** [comment]
Oh so it indent the level by the number of white space that I have used. So, I just have to change the value of sw or the number white  space that I always use to go to the new level in my code and it will be ok.

Thank you. I really appreciate your help.  It work just fine now
![screenshot from 2017-10-10 11-52-41](https://user-images.githubusercontent.com/27545565/31367426-4dec2854-adb2-11e7-8eaf-6e00e6169ad3.png)
