### ISSUE TITLE
Feature request: highlight local indent like local-indent.vim

### ISSUE THREAD

**Issue by kepbod** [Yggdroot/indentLine#225]
If there is an option that could highlight the local indent character, it would be great. There is a repo called [local-indent.vim](https://github.com/tweekmonster/local-indent.vim) with this function, but it could not highlight the character.

**Comment by Yggdroot** [comment]
This issue is similar with issue #87, can not be achieved by vim.

**Comment by kepbod** [comment]
Thx!
