### ISSUE TITLE
Big Bug

### ISSUE THREAD

**Issue by ProZoom** [Yggdroot/indentLine#227]
when I open java file，this is like it；
if I uninstall this Bundle，it is ok！
![9C9BF3BD5FB2668B7734D9D4F9A22233.jpg](http://upload-images.jianshu.io/upload_images/5681277-073694e84e359b27.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by Yggdroot** [comment]
`let g:indentLine_char = '|'`, and have a try.

**Comment by mblarsen** [comment]
Great issue title 🙊

**Comment by Yggdroot** [comment]
Close as no response.

**Comment by ProZoom** [comment]
it is not work too
