### ISSUE TITLE
IndentLine shows only in white color at start until changing colorscheme

### ISSUE THREAD

**Issue by qdddddd** [Yggdroot/indentLine#228]
Each time I open a file in vim, the indent lines are displayed in white (bright) color as shown in the picture below, without any color settings for the indentLine plugin.

![screen shot 2017-11-20 at 7 04 36 pm](https://user-images.githubusercontent.com/15933639/33015722-c36feb62-ce26-11e7-9c4a-e0c4b34896f5.png)

Commands like :IndentLinesDisable and :IndentLinesEnable, or :IndentLinesReset do not solve the problem. However, the color is set to the default grey if I change to another colorscheme:

![screen shot 2017-11-20 at 7 07 22 pm](https://user-images.githubusercontent.com/15933639/33015725-c619ecaa-ce26-11e7-8bcb-ecb27cb0022f.png)

... and change back:

![screen shot 2017-11-20 at 7 08 02 pm](https://user-images.githubusercontent.com/15933639/33015732-cb466636-ce26-11e7-86f6-976fea9b12c2.png)

Below are the settings in my .vimrc:

    " IndentLine plugin
    let g:indentLine_enabled = 1
    let g:indentLine_faster = 1
    let g:indentLine_char = ‘⎸'

    " Set displays depending on filetype 
    function! SetDefaultDisplays()
        set background=dark
        if has('gui_running')
            colo materialtheme
        else
            colo materialbox
            set term=xterm-256color
        endif
        let g:airline_theme = 'base16_mocha'
        let b:AutoPairs={'(':')', '[':']', '{':'}',"'":"'",'"':'"', '`':'`'}
        set guifont=Monaco\ for\ Powerline
        AirlineRefresh
    endfunction

    function! SetTexDisplays()
        set background=light
        colorscheme solarized
        set guifont=Cousine\ for\ Powerline:h14
        "set conceallevel=0
        let g:airline_theme='solarized'
        let b:AutoPairs={'(':')', '[':']', '{':'}',"'":"'",'"':'"', '`':'`', '$':'$'}
        AirlineRefresh
    endfunction

    function! SetDisplays()
        if (&ft=='tex')
            call SetTexDisplays()
        else
            call SetDefaultDisplays()
        endif
    endfunction

    au! BufEnter,FileType * call SetDisplays()

MacVim version:

    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2017 02:39:16)
    macOS version
    Included patches: 1-1272
    Compiled by root@Traviss-Mac-713.local
    Huge version with MacVim GUI.  Features included (+) or not (-):
    +acl             +cursorbind      +fullscreen      +modify_fname    +path_extra      +syntax          +visualextra
    +arabic          +cursorshape     -gettext         +mouse           +perl/dyn        +tag_binary      +viminfo
    +autocmd         +dialog_con_gui  -hangul_input    +mouseshape      +persistent_undo +tag_old_static  +vreplace
    +balloon_eval    +diff            +iconv           +mouse_dec       +postscript      -tag_any_white   +wildignore
    +browse          +digraphs        +insert_expand   -mouse_gpm       +printer         -tcl             +wildmenu
    ++builtin_terms  +dnd             +job             -mouse_jsbterm   +profile         +termguicolors   +windows
    +byte_offset     -ebcdic          +jumplist        +mouse_netterm   +python/dyn      +terminal        +writebackup
    +channel         +emacs_tags      +keymap          +mouse_sgr       +python3/dyn     +terminfo        -X11
    +cindent         +eval            +lambda          -mouse_sysmouse  +quickfix        +termresponse    -xfontset
    +clientserver    +ex_extra        +langmap         +mouse_urxvt     +reltime         +textobjects     +xim
    +clipboard       +extra_search    +libcall         +mouse_xterm     +rightleft       +timers          -xpm
    +cmdline_compl   +farsi           +linebreak       +multi_byte      +ruby/dyn        +title           -xsmp
    +cmdline_hist    +file_in_path    +lispindent      +multi_lang      +scrollbind      +toolbar         -xterm_clipboard
    +cmdline_info    +find_in_path    +listcmds        -mzscheme        +signs           +transparency    -xterm_save
    +comments        +float           +localmap        +netbeans_intg   +smartindent     +user_commands
    +conceal         +folding         +lua/dyn         +num64           +startuptime     +vertsplit
    +cryptv          -footer          +menu            +odbeditor       +statusline      +virtualedit
    +cscope          +fork()          +mksession       +packages        -sun_workshop    +visual

Same problem occurs on both of my two Mac machines sharing the same .vimrc file. Appreciate any help!

**Comment by qdddddd** [comment]
Tried the solution in #177 but does not work either.

**Comment by Yggdroot** [comment]
Remove `au! BufEnter,FileType * call SetDisplays()` and have a try.

**Comment by qdddddd** [comment]
After trials, I found that any setting for the colorschemes inside the autocmd with event BufEnter or BufWinEnter will cause the problem. The indent lines perform normally if I move the “color” and “set background” out of the autocmd, or remove the trigger “BufEnter” from the autocmd. So I guess it’s the problem of the ordering between when the indentLine sets color and when the BufEnter event is triggered.

**Comment by qdddddd** [comment]
Solved by modifying Line 337 of indentLine/after/plugin/indentLine.vim:

Initial code:

`autocmd BufRead,BufNewFile,ColorScheme,Syntax * call <SID>InitColor()`

Modified:

`autocmd BufEnter,BufRead,BufNewFile,ColorScheme,Syntax * call <SID>InitColor()`
