### ISSUE TITLE
setConceal & expandtab issue

### ISSUE THREAD

**Issue by Mamad026** [Yggdroot/indentLine#232]
Hi there.
I have two questions! [please don't mind, I'm newbie :( ]
1. What  do you mean about 

> If you want to keep your conceal setting, put this line to your vim dotfile:

and what does `let g:indentLine_setConceal = 0` exactly do? (because when I stick it to my .vimrc indentLine will off and haven't any vertical lines, why?)

2. When I set indentLine on it overrides `expandtab` option. why does it happen and is there any way to keep expand tab effect on?

Please let me know about them.
Thanks.

**Comment by Yggdroot** [comment]
1. `:h conceal`
If you did not encounter any issue about `conceal`, please ignore `g:indentLine_setConceal`, keep it as default.
2. indentLine never overrides `expandtab`.

**Comment by Mamad026** [comment]
Thanks for respon.
Good luck.
