### ISSUE TITLE
Something goes wrong when I open my .json files.

### ISSUE THREAD

**Issue by authorcamus** [Yggdroot/indentLine#238]
In my vimrc file, I  have "set cursorline cursorcolumn".
When I open a json file with this plugin off:
![screenshot from 2018-03-16 16-49-43](https://user-images.githubusercontent.com/19421172/37511643-971888fc-293a-11e8-8703-f5d4e7edda4d.png)
While with it on:
![screenshot from 2018-03-16 17-00-44](https://user-images.githubusercontent.com/19421172/37511964-a49be84c-293b-11e8-8d2c-acda8c8079e0.png)
(1)My double quotation disappers
(2)My cursor gets into a mess
How can I solve the problem? Thanks.

**Comment by Yggdroot** [comment]
Please refer to issue #140 .
