### ISSUE TITLE
Command output not shown when indentLine is enabled

### ISSUE THREAD

**Issue by robinmitra** [Yggdroot/indentLine#241]
As the title says, when `indentLine` is enabled, command output isn't displayed. For example, if I type `colorscheme` and hit carriage return, the output value (i.e. name of the current theme) isn't displayed/visible.

However, if I disable `indentLine` plugin, or if I set the following flag, command output value is shown again like it should:
`let g:indentLine_setConceal = 0`

Example of running `colorscheme` with the above flag (notice the colour scheme `gruvbox`):
<img width="631" alt="screen shot 2018-04-17 at 14 53 17" src="https://user-images.githubusercontent.com/3193694/38874059-2265aade-424f-11e8-8813-fb5ebd060e0e.png">

And without the flag:
<img width="541" alt="screen shot 2018-04-17 at 14 55 11" src="https://user-images.githubusercontent.com/3193694/38874194-72ecb934-424f-11e8-832c-d7510524b20c.png">

Note that this happens for all commands, not just `colorscheme`.

**Comment by Yggdroot** [comment]
Sorry, I can not reproduce this issue.

**Comment by robinmitra** [comment]
TBH, even I cannot seem to be able to reproduce this any more, which is quite strange. I'll close this for now, and re-open if I can reproduce it with more information.
