### ISSUE TITLE
两次缩进之后，光标无法到达行末

### ISSUE THREAD

**Issue by GooCoder** [Yggdroot/indentLine#245]
请看下面这种情况，黄色光标无法到达行末。
![image](https://user-images.githubusercontent.com/39628662/41575426-f2745c02-73b4-11e8-9a84-f3a7e54387e6.png)

但是一级缩进(也就是第一个print语句)可以到达行末。

**Comment by GooCoder** [comment]
实际上，光标已经是到了行末的，只是显示问题。。希望尽快修复这个bug。。

**Comment by Yggdroot** [comment]
这如果是个bug就是vim的bug，你可以换个字符。
`¦, ┆, │, ⎸`.

**Comment by GooCoder** [comment]
确实是字符设置的问题，谢谢了
