### ISSUE TITLE
Great plugin, but how can I copy my code  

### ISSUE THREAD

**Issue by ksantr** [Yggdroot/indentLine#246]
Is it possible to copy without selecting code in visual mode?

**Comment by Yggdroot** [comment]
Sorry, I don't understand your question, is it related to indentline?

**Comment by jessarcher** [comment]
I believe the question was about how to highlight and select code in the terminal without copying the indentLine characters (and without using visual mode which won't copy code into the local clipboard on a remote ssh session).

I've found the only way to do this is to temporarily toggle IndentLine off with `:IndentLinesToggle`.

There are a few other characters that get copied if you select text with the terminal so I created the following mapping to toggle them all on and off:

```vim
nmap <leader>l :setlocal number!<CR>:setlocal list!<CR>:silent! GitGutterToggle<CR>:silent! setlocal relativenumber!<CR>:silent! IndentLinesToggle<CR>
```

Hope that helps, @ksantr

**Comment by ksantr** [comment]
Yes @jessarcher , you are right
