### ISSUE TITLE
How to set up like the last photo, i.e. with leading spaces and vertical line together?

### ISSUE THREAD

**Issue by wingbui** [Yggdroot/indentLine#256]
I try to make indentLine works likw the last photo but do not know how; It is not mentioned in the usage. Please help set up indentLine like the last photo: leading spaces and vertical line together.

Thanks!

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/indentLine/blob/81096235522e2aa49c2059e8e02e8d6f359c1d34/doc/indentLine.txt#L176-L183

**Comment by wingbui** [comment]
Oh, I missed that. It’s awesome! Thank you!
