### ISSUE TITLE
set indentLine_color_term does not work as expected

### ISSUE THREAD

**Issue by jdhao** [Yggdroot/indentLine#257]
I am using Neovim 0.3.1 on Mac.  I installed a dozen of plugins with vim-plug. I have found that  the following setting does not change the indent line color:

```
 let g:indentLine_color_term = 226
```

But if I create a minimal config file `nvim.config` with following content:

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'Yggdroot/indentLine'
call plug#end()

let g:indentLine_color_term = 226
```
and start nvim with `nvim -u nvim.config some_code.py`, the above setting will work.

On the other hand, if I use gui vim color setting in the full nvim config file:

```
let g:indentLine_color_gui = '#A4E57E'
```
, the indent line color will also change. But, isn't this setting for GUI vim? Neovim is not GUI vim.

Could you shed some light on what is happening?

**Comment by jdhao** [comment]
After some comparison between different settings, I have found that the above behaviour is related to if `termguicolors` is set in Neovim.  Here is a table summary:

|neovim setting/indentLine setting|set variable `indentLine_color_gui`| set variable `indentLine_color_term`|
|---|---|---|
|`set termguicolors`| **works**|  does not work|
|`set notermguicolors`|does not work| **works**|

Is this the indented behaviours?

**Comment by Yggdroot** [comment]
I works as designed, please refer to `:h termguicolors`.

**Comment by jdhao** [comment]
From the indentLine doc:
```
g:indentLine_color_gui                          *g:indentLine_color_gui*
                Specify GUI vim indent line color.
```

This description confuses me because it says `indentLine_color_gui` is used to `specify GUI vim indent line color`. I am using terminal Neovim, which is not GUI vim.

**Comment by Yggdroot** [comment]
Why do you set termguicolors?

**Comment by Yggdroot** [comment]
If you do not know why set termguicolors, please do not set it.

**Comment by jdhao** [comment]
I set termguicolors because my terminal (iterm2) supports true colors. To enable true color support, I need to use `set termguicolors`.

**Comment by jdhao** [comment]
The following is what I thought:

Even if I have set termguicolors, neovim is still terminal vim. According to documentation of indentLine, I should use `indentLine_color_term` variable to set indent line color, because this setting is for terminal vim.

Is the above reasoning wrong? Maybe I have misunderstood what `GUI vim` mean?

**Comment by Yggdroot** [comment]
```
'termguicolors' 'tgc'	boolean (default off)
			global
	When on, uses |highlight-guifg| and |highlight-guibg| attributes in
	the terminal (thus using 24-bit color). Requires a ISO-8613-3
	compatible terminal.
```
When on, uses |highlight-guifg| and |highlight-guibg| attributes in the terminal, g:indentLine_color_gui is corresponding to gui attributes. You have already forced term vim to use gui attributes, why do not want  indentLine to abide by this rule.
