### ISSUE TITLE
Show indentline_char at first character like tabs

### ISSUE THREAD

**Issue by Hacksaurus** [Yggdroot/indentLine#263]
Hello!
Is it possible to show the character to show tabs as the first one, then repeat?
Let me show you what I mean:
![screenshot_2018-12-29_15-35-27](https://user-images.githubusercontent.com/24832107/50542620-63862a80-0b7f-11e9-98ef-4b6a3f0b8b4b.png)
This is the current behavior, and its nice and all, but it doesn't show that one "tab" I have on line 14
Versus in this older screenshot where I use tabs it shows the tab at the very beginning:
![image](https://user-images.githubusercontent.com/24832107/50542637-a811c600-0b7f-11e9-885a-30e3101a56fe.png)
And actually shows the tabs at line 45, and 48 on the right side of that screenshot
Thanks for any help!

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/indentLine/blob/80f4acdfab361407d449a3b3e12130217dd0d2a1/doc/indentLine.txt#L39-L44

**Comment by Hacksaurus** [comment]
Exactly what I was looking for, but the lines you sent me (79-83) are not the same on the doc
