### ISSUE TITLE
Side effect: code block syntax error in markdown

### ISSUE THREAD

**Issue by laggardkernel** [Yggdroot/indentLine#264]
Code block syntax line beginning with ``` is not displayed when indentLine is enabled.

**Comment by Yggdroot** [comment]
Can not reproduce. It must be a conflict with other plugin.

**Comment by laggardkernel** [comment]
You're right. Just found it's a conflict between indentLine and plasticboy/vim-markdown.

**Comment by larrybotha** [comment]
A note to anyone else coming across this, the same happens with `sheerun/vim-polyglot` in markdown files.

Disabling `indentLine` for markdown files, as per https://github.com/Yggdroot/indentLine/issues/78#issuecomment-152849114, appears to be a workaround.
