### ISSUE TITLE
not working (same old)

### ISSUE THREAD

**Issue by Mehechiger** [Yggdroot/indentLine#265]
Hello, the same old issue, but indentLine is not working on my vim... Here's what I've done to check up and infos I collected, thanks:

I'm using spaces
(note that in some of the pics the indents shown are actually the tab ones and are set up by set list lcs=tab:\|\<space>)

vim --version
![screen shot 2019-02-17 at 16 04 30](https://user-images.githubusercontent.com/13514897/52914919-27915b00-32ce-11e9-9da8-2c28afd9e37a.png)

:IndentLinesToggle
E492: Not an editor command: IndentLinesToggle

and my vimrc
![screen shot 2019-02-17 at 16 06 20](https://user-images.githubusercontent.com/13514897/52914934-47c11a00-32ce-11e9-8228-8a2d45543580.png)
![screen shot 2019-02-17 at 16 06 30](https://user-images.githubusercontent.com/13514897/52914935-4859b080-32ce-11e9-9ec0-1c015616583d.png)
![screen shot 2019-02-17 at 16 06 43](https://user-images.githubusercontent.com/13514897/52914936-4859b080-32ce-11e9-9a6d-f02b358dff3c.png)
![screen shot 2019-02-17 at 16 06 49](https://user-images.githubusercontent.com/13514897/52914937-4859b080-32ce-11e9-8e60-c770a339de47.png)
![screen shot 2019-02-17 at 16 06 55](https://user-images.githubusercontent.com/13514897/52914938-4a237400-32ce-11e9-841a-44f96995e165.png)
![screen shot 2019-02-17 at 16 07 00](https://user-images.githubusercontent.com/13514897/52914939-4a237400-32ce-11e9-95ce-1ca03e836f3a.png)
![screen shot 2019-02-17 at 16 07 04](https://user-images.githubusercontent.com/13514897/52914940-4abc0a80-32ce-11e9-8129-6ded84f19ae5.png)

**Comment by Yggdroot** [comment]
Why do you set `let g:indentLine_loaded = 1` ? please remove it.

**Comment by Mehechiger** [comment]
> Why do you set `let g:indentLine_loaded = 1` ? please remove it.

Thanks it worked after removing the line. But in your help doc is written:
"g:indentLine_loaded                              g:loaded_indentLine
        │       Whether load indentLine plugin.
        │       Default value is 0.
"
I thought value 1 means to load the plugin...
