### ISSUE TITLE
different char for different indent levels

### ISSUE THREAD

**Issue by skyblueee** [Yggdroot/indentLine#266]
I get that it is impossible to make a rainbow indentLine after having searched previous issues. But is it possible for different char for different indent levels? If so, then I can set:
let g:indentLine_1st_char=‘|’
let g:indentLine_2nd_char=‘¦’
let g:indentLine_3rd_char=‘┆’
let g:indentLine_4th_char=‘┊’
(I read the help file but only find g:indentLine_first_char)
As it is impossible to be colorful, I think my suggestion might be a bit meaningful.

**Comment by Yggdroot** [comment]
Done.

https://github.com/Yggdroot/indentLine/blob/47648734706fb2cd0e4d4350f12157d1e5f4c465/doc/indentLine.txt#L30-L35

**Comment by skyblueee** [comment]
Wow! Thanks for your awesome speed. I have updated the plug and that is exactly what I want.
