### ISSUE TITLE
Indent Lines stops working after shiftwidth is changed and :IndentLinesReset does nothing

### ISSUE THREAD

**Issue by Braber01** [Yggdroot/indentLine#268]
after having indent lines installed for a while the lines are no longer showing up, when I have changed my shiftwidth, even after using the :IndentLinesReset command is there any way I can fix this? also :IndentLinesToggle does nothing as well

**Comment by Yggdroot** [comment]
I can not reproduce this issue.

**Comment by Braber01** [comment]
I think it might be a problem or conflict with a plugin, I tend to also spend most of my time in the terminal let me copy my .vimrc and show you that.

**Comment by Braber01** [comment]
https://pastebin.com/txwCat9H here's my .vimrc

**Comment by Yggdroot** [comment]
Why are there two indentLine? Please notice line 19 and line 43.
