### ISSUE TITLE
Indents begin to shine in light gray color at bufWritePost

### ISSUE THREAD

**Issue by dementor5** [Yggdroot/indentLine#270]
If i open config ~/.vimrc and save it twice `:w`, all indents begin to shine in light gray color.
If I execute the command `:source ~/.vimrc` manually, everything returns to normal.
![vimNormalColorOfIndents](https://user-images.githubusercontent.com/22612354/55957910-21857e00-5c70-11e9-97e6-d8855c788b9d.png)
![vimShiningIndents](https://user-images.githubusercontent.com/22612354/55957915-25190500-5c70-11e9-85c4-8b8878a40ee6.png)

minimal .vimrc for error reproduction:
```
call plug#begin('~/.vim/plugged')
                Plug 'Yggdroot/indentLine'
call plug#end()

                let g:indentLine_leadingSpaceEnabled = 1

                colorscheme desert

if has("autocmd")
                autocmd! BufWritePost .vimrc source $MYVIMRC
endif


" autoread vim config
if has("autocmd")
  autocmd! BufWritePost .vimrc source ~/.vimrc
endif
```

**Comment by Yggdroot** [comment]
It is easy to explain that `colorscheme desert` changed the color of `conceal`.

You can see the output of `:verbose hi conceal`.

**Comment by dementor5** [comment]
> It is easy to explain that `colorscheme desert` changed the color of `conceal`.
> 
> You can see the output of `:verbose hi conceal`.

Thank you, your advice  helped me to solve a problem.
Would be great if in a plug-in there would be a built-in decision...

There is my working config:
```
call plug#begin('~/.vim/plugged')
  Plug 'Yggdroot/indentLine'
  some other plugins...
call plug#end()

" indentLine
let g:indentLine_leadingSpaceEnabled = 1

" to check values for restore run :verbose highlight conceal
function! s:restoreIndentLightsHighlight()
  highlight conceal ctermfg=239 guifg=Gray30
endfunction

some other config lines...

function! s:postReload()
  silent :call s:restoreIndentLightsHighlight()
endfunction

" autoreload vim config
if has("autocmd")
 autocmd! BufWritePost .vimrc,init.vim source $MYVIMRC | :call s:postReload()
endif
```

**Comment by dementor5** [comment]
Perhaps it will be useful for someone - I found more interesting solution:
```
if has("autocmd")
 au! BufWritePost .vimrc,init.vim nested so $MYVIMRC
en
```
