### ISSUE TITLE
How to show characters for all spaces

### ISSUE THREAD

**Issue by chinmaychhajed** [Yggdroot/indentLine#277]
Hello,

This plugin is working perfectly with vim except one thing. I need to see some character (which I have set to `·` using `let g:indentLine_leadingSpaceChar = '·'`) for all the spaces used in file, not just indentation spaces. Please guide how this can be done.

If this feature is out of scope of this plugin, then please let me know which other feature of vim / plugin I can use to enable this. Thanks in advance.

**Comment by Yggdroot** [comment]
You can refer to here:
https://github.com/vim/vim/blob/6f72e90dd843a7342395b31f31c2073a3859869d/runtime/doc/options.txt#L4763-L4842

For example,
```vim
set list
set lcs=tab:>-,eol:$,space:.
```

**Comment by chinmaychhajed** [comment]
Thanks.
