### ISSUE TITLE
Where can I find color codes for `g:indentLine_color_term`

### ISSUE THREAD

**Issue by chhajedji** [Yggdroot/indentLine#280]
Hello,

I need to change color codes for line indent character. I'm using `g:indentLine_color_term` for this. But I'm unable to find which color code corresponds to which number. 

Please help. Thanks in advance.

**Comment by Fuzzier** [comment]
vim-scripts/xterm-color-table.vim

**Comment by chhajedji** [comment]
Okay, https://github.com/vim-scripts/xterm-color-table.vim this.
