### ISSUE TITLE
indentLine disappear under visual mode highlight

### ISSUE THREAD

**Issue by jrwrigh** [Yggdroot/indentLine#285]
As shown here, the indent lines disappear when there are under the visual mode highlight.
![image](https://user-images.githubusercontent.com/20801821/68821184-d76fdb00-064a-11ea-93c1-b122311287fb.png)

I'm guessing it's because the highlight color and the line color are the same. Is the only option to change the coloring of the indent lines?

**Comment by Yggdroot** [comment]
`set concealcursor+=v`

**Comment by jrwrigh** [comment]
It's ugly, but it gets the job done.
![image](https://user-images.githubusercontent.com/20801821/68827451-4b1be300-065f-11ea-9167-b8fd003fde3c.png)
