### ISSUE TITLE
disable indent line when viewing diff

### ISSUE THREAD

**Issue by pirey** [Yggdroot/indentLine#289]
![2020-02-11-150534_1366x768_scrot](https://user-images.githubusercontent.com/10344542/74219694-224bce00-4ce0-11ea-8004-42640630774e.png)

as shown in the picture, the indent line highlighting doesn't match highlight for diff line,
is it possible to get the same highlight for diff lines? 
or can i somehow disable the indent line when i'm opening a diff?

i'm using fugitive-vim :Gdiffsplit feature for the diff

**Comment by kazhala** [comment]
I did something like this to disable indent-lines in diff mode, works with fugitive Gdiffsplit
`augroup DiffHideIndent
  autocmd!
  " Disable indentline in vim diffmode
  autocmd OptionSet diff IndentLinesDisable
augroup end
`

**Comment by pirey** [comment]
hi @kazhala , 
i tried your solution and it only work when i open a diff,
the problem is when i close the diff, indentLine is still disabled

do you know any autocmd event or option to revert it?

**Comment by pirey** [comment]
based on your suggestion, 
i tried something like this

```vim
augroup custom_indentLine
    autocmd!
    autocmd OptionSet diff call ToggleIndentLine()
augroup END

function! ToggleIndentLine()
    if &diff
        execute 'IndentLinesDisable'
    else
        execute 'IndentLinesEnable'
    endif
endfunction
```
the indent line is disabled when i open a diff, but when i close diff window, the indent line still disabled. 

i have confirmed that the &diff option changed back to 0, but  it seems neovim doesn't detect when the &diff option set back to 0

**Comment by kazhala** [comment]
> do you know any autocmd event or option to revert it?

Sadly no, I remember I was facing the issue as well not being able to set it back.

**Comment by Yggdroot** [comment]
Fixed.

**Comment by pirey** [comment]
![2020-03-02-175716_1366x768_scrot](https://user-images.githubusercontent.com/10344542/75670427-4a12ce00-5caf-11ea-9afa-cb66bff5c979.png)
it works, thanks

**Comment by koallen** [comment]
This is breaking my NERDTree startup on `VimEnter` because the cursor now stays on the empty buffer instead of the NERDTree window.

**Comment by Yggdroot** [comment]
@koallen Fixed.
