### ISSUE TITLE
How to turn off highlight indent when create a new line?

### ISSUE THREAD

**Issue by cellardoorver** [Yggdroot/indentLine#291]
<img width="428" alt="Screenshot 2020-02-25 at 10 41 48" src="https://user-images.githubusercontent.com/57286496/75213180-eaeb2000-57bb-11ea-94ad-08b84611349f.png">
As picture above shown, it's such a real annoy when i have to deal with it all the time

**Comment by Yggdroot** [comment]
I don't think it is related to indentline.
