### ISSUE TITLE
Incompatible with tmux 3a

### ISSUE THREAD

**Issue by maharjanaman** [Yggdroot/indentLine#292]
I upgraded tmux to version 3a and when I add `let g:indentLine_leadingSpaceEnabled=1` it behaves weirdly.
![Kapture 2020-03-02 at 13 34 37](https://user-images.githubusercontent.com/14164484/75655970-145bee00-5c8b-11ea-8b1d-3c741b144d92.gif)

**Comment by Yggdroot** [comment]
What do you mean by `weirdly`?

**Comment by maharjanaman** [comment]
I did attached gif. See how indentation changes and duplicate values appear on line change.

**Comment by cprn** [comment]
I confirm there's a rendering issue but I think it's in `tmux`. Version 3.0 is alpha, let's hope it won't be there in beta. If you haven't yet, please, open an issue in `tmux` project bug tracker.

**Comment by maharjanaman** [comment]
Seems this issue is not happening with tmux 3.1. Closing this for now.
