### ISSUE TITLE
AutoResetWidth breaks exclude options

### ISSUE THREAD

**Issue by lukas-reineke** [Yggdroot/indentLine#301]
`s:AutoResetWidth()` checks `enable` from both buffer and global `indentLine_enabled` variable.
https://github.com/Yggdroot/indentLine/blob/15aceda8c4eea621b66faa8673fca0b9fbe2f457/after/plugin/indentLine.vim#L268-L272

And then writes this value to the buffer `indentLine_enabled` variable.
https://github.com/Yggdroot/indentLine/blob/15aceda8c4eea621b66faa8673fca0b9fbe2f457/after/plugin/indentLine.vim#L280

This breaks excluded filetypes/buftypes/bufnames because all buffers are now explicitly enabled and skip the filter.
https://github.com/Yggdroot/indentLine/blob/15aceda8c4eea621b66faa8673fca0b9fbe2f457/after/plugin/indentLine.vim#L326

**Comment by polyzen** [comment]
Seems this is fixed in general, though I still have issues with indentLine exclusions not working in Terminal-Normal mode (`buftype=terminal`, `filetype=`) and when viewing commits that were pulled with vim-plug (`buftype=git`, `filetype=nofile`).

**Comment by lukas-reineke** [comment]
fixed in https://github.com/Yggdroot/indentLine/pull/311
