### ISSUE TITLE
let g:indentLine_char has no effect

### ISSUE THREAD

**Issue by jkehler** [Yggdroot/indentLine#304]
I tried setting a custom character using `let g:indentLine_char='c'` and it has no effect. I've tried various letters and it just stays as the same character. Any ideas why I cannot change the character?

**Comment by Yggdroot** [comment]
I don't know, I think it is not indentLine's fault.

**Comment by jkehler** [comment]
Yeah you're right. For some reason its working now and I have no idea why. I started with disabling all of my plugins and then it worked. So then I started re-enabling them one by one to see which was the culprit. But in the end I re-enabled ALL of my existing plugins and it was still working...so thus no conclusion was made why it didn't work originally.
