### ISSUE TITLE
Provide separate highlight style for current scope

### ISSUE THREAD

**Issue by CallumHoward** [Yggdroot/indentLine#305]
In vscode the indent guide for the current scope is styled differently with a highlighted color. Would it be possible to implement this as an option?

<img width="402" alt="Screen Shot 2020-05-02 at 4 58 04 pm" src="https://user-images.githubusercontent.com/7144420/80857507-198ee680-8c96-11ea-967e-fe3628b3176d.png">

**Comment by Yggdroot** [comment]
This feature can not be implemented, because there is only one way to hightlight the indentLine, `hi Conceal`.

**Comment by CallumHoward** [comment]
Right, that's too bad. Thanks
