### ISSUE TITLE
It display the default char only when there is a comment

### ISSUE THREAD

**Issue by liamcaccetta** [Yggdroot/indentLine#310]
I just installed it via PlugInstall.
It doesn't work, except for comments.

There a screenshot of the issue. 

<img width="546" alt="screenshot" src="https://user-images.githubusercontent.com/42863651/82907659-2df99280-9f67-11ea-9b1b-6ea1985b9334.png">

If you need some more detail, just ask.

**Comment by Yggdroot** [comment]
have you read #59?

**Comment by liamcaccetta** [comment]
@Yggdroot no, but I figured out the problem, it was because of using tabs insted of spaces. I'll read the #59 and I'll see if I could manage to solve the problem. If I couldn't, I'd write back here.

**Comment by liamcaccetta** [comment]
I've read #59 and tried everything is written there, but I couldn't manage to find a solution. Is it a problem of the plugin with tabs? Should I switch to spaces? (I won't, tabs >>>>>>>> spaces :) )
