### ISSUE TITLE
Indentation lines only appearing every other tab, and only at the last tab.

### ISSUE THREAD

**Issue by thorlucas** [Yggdroot/indentLine#314]
My indent lines only appear at every *other* indent level (at 2, at 4, at 6, etc), and only the last indent level is showing up. If something has three tabs, only the 2 shows up. If something has 5 tabs, only the 4 shows up. Here's a screenshot:

<img width="439" alt="Screen Shot 2020-06-05 at 2 00 15 PM" src="https://user-images.githubusercontent.com/25698466/83922281-e3310500-a734-11ea-9167-7ecb587ebfe0.png">

I would expect something that looks like this (courtesy of sublime text):

<img width="746" alt="Screen Shot 2020-06-05 at 2 02 05 PM" src="https://user-images.githubusercontent.com/25698466/83922425-255a4680-a735-11ea-8bef-ceb082550f52.png"> 

Here is what my `init.vim` looks like:
```
" IndentLine {{
let g:indentLine_char = '┊'
let g:indentLine_setColors = 0
"}}
```

**Comment by Yggdroot** [comment]
make sure the other places are spaces but not tab.  set correct value to sw.

**Comment by thorlucas** [comment]
Thanks, you're right I was using tabs. Enabling both what you have in your readme for when I'm using tabs and also indentline for when I'm using spaces seems to work.
