### ISSUE TITLE
Doesn't show the default info in neovim

### ISSUE THREAD

**Issue by SKrPl** [Yggdroot/indentLine#315]
* Neovim version: 0.4.3
* Minimal neovim config
```
call plug#begin('~/.config/nvim/bundle')

Plug 'Yggdroot/indentLine'

call plug#end()
```

* Current behaviour: It doesn't show neovim info when stating neovim.
![Screenshot from 2020-06-13 02-30-44](https://user-images.githubusercontent.com/12163892/84545988-f1c38180-ad1d-11ea-9ab5-2481df943f54.png)

* Expected behaviour: It should show the info when starting neovim, this is the output after commenting out `Plug 'Yggdroot/indentLine'`.
![Screenshot from 2020-06-13 02-32-33](https://user-images.githubusercontent.com/12163892/84546099-28999780-ad1e-11ea-97b8-bcd59c56c062.png)

**Comment by ndavidpsi** [comment]
@SKrPl have you figured it out? I have the same issue

**Comment by Yggdroot** [comment]
Update the plugin, then add this line in vimrc:
```vim
autocmd VimEnter * if bufname('%') == '' | IndentLinesDisable | endif
```

**Comment by ndavidpsi** [comment]
Solved it for me. Thanks!!
