### ISSUE TITLE
Not showing lines between \n separated lines

### ISSUE THREAD

**Issue by xradiation** [Yggdroot/indentLine#319]
![Screenshot_2020-07-05_20-53-07](https://user-images.githubusercontent.com/61669101/86541052-9db55280-bf01-11ea-8a2e-30cec8514a28.png)

is there is a way to solve the discountinuity in the lines as shown above ?

also why the code structure must be perfectly right for the plugin to work at all, in other words i use a code prettifier `coc-prettier` in order to bringe the code to the right shape and only then `indentLine` starts to make sense where to put the indent lines.

is there is any way so that the `indentLine` shows the indentation lines regardless of the code structure?
( Note : VSCode is perfectly capable of doing that ), this is really helpfull to spot some missing opening or closing tags or brackets here and there.

Amazing plugin BTW @Yggdroot, appreciated.

Any help is much appreciated.

**Comment by Yggdroot** [comment]
IndentLine shows indent lines according to `shiftwidth` and `tabstop`, if you are not satisfied with the place showing the indent lines , it is probable that you don't set the value of `shiftwidth` properly.

the discountinuity can not be solved.

**Comment by xradiation** [comment]
thanks alot for the replay @Yggdroot,
as for the discountinuity issue I guess I've found a way around it, simply by filling in the new lines with spaces as needed.

here is an example : 
- before : 
![Screenshot_2020-07-06_11-14-45](https://user-images.githubusercontent.com/61669101/86583057-89fa0280-bf7a-11ea-9d2e-3fc1af8186a4.png)

- After : 
![Screenshot_2020-07-06_11-16-04](https://user-images.githubusercontent.com/61669101/86583078-91b9a700-bf7a-11ea-9ca4-f077c5df6a92.png)

however am not entirely sure how to implement such thing, since am not into vim plugins scripting; I genuinely think that I'ts doable so I might possibly give it a try using some sort of a bash / python script.

and it would be amazing if this can be done right in `indetLine` plugin.

Best regard

**Comment by bluz71** [comment]
> the discountinuity can not be solved.

The [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) plugin cleverly uses Neovim's [virtual text](https://github.com/neovim/neovim/pull/8180) feature to render indent markers on blank lines. This is a [Neovim](https://github.com/neovim/neovim) only feature.

@xradiation, I would not recommend inserting spaces, check out the [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) plugin in combination with Neovim.

P.S. I have no affiliation with the indent-blankline plugin.

**Comment by xradiation** [comment]
well, it's kind of strange that I've actually never heard of this plugin before, but I guess here we go.
am really greatful @bluz71 for your suggestion, it does exactly what I wanted to do : 

![Screenshot_2020-07-07_11-58-50](https://user-images.githubusercontent.com/61669101/86770845-3e625a00-c049-11ea-9c2b-d2a1585ceb0f.png)

however, as it seems in lines `+1` & `+8` at the `second` and `fourth` columns respectively, the plugin has some strage "bug" where it's not supposed to render indent lines, any ways it's just a little thing that I can live with for now.

I really hope that @Yggdroot will merge this plugin, if possible that is.
again really appreciated you help @bluz71 , @Yggdroot .
