### ISSUE TITLE
Feature Request Indentation Colors

### ISSUE THREAD

**Issue by typkrft** [Yggdroot/indentLine#323]
First off, let me say thank you for this wonderful plugin. After moving from a GUI text editor this was something I was definitely missing. 
--------------------------------------------
I think it would awesome if the user could define colors for indentation levels. 

For Example:
```
  | <= red
    | <= green
      | < = yellow 
    | <= green
  | <= red   
```

**Comment by Shaedil** [comment]
I second this notion, I think this functionality best fits the trend in functionality over aesthetics in vim plugins. No doubt, I would use this and I'm willing to work on this functionality if this is something to be considered in the next update.

**Comment by Yggdroot** [comment]
There is no way for this feature, because the line is attached to `conceal` highlight group.
