### ISSUE TITLE
Too many vertical lines

### ISSUE THREAD

**Issue by josephmturner** [Yggdroot/indentLine#330]
Hello! I'm excited to start using this plugin, but I'm running into an issue where the vertical lines are appearing on every single space (as opposed to every other space, the expected behavior).

![image](https://user-images.githubusercontent.com/50191376/96540427-96b51480-1252-11eb-93af-4c730495099d.png)

I am using spaces for indenting.

**Comment by Yggdroot** [comment]
What programming language is it?
It's a confilict with the syntax file of the programming language, maybe you can find the solution in the existing issues.

**Comment by josephmturner** [comment]
Thank you for the response. The syntax is React JSX with Typescript - I will look in the issues, but if you would point me to an issue, I would greatly appreciate it :)

**Comment by josephmturner** [comment]
I am using the vim-javascript plugin, and in [this comment](https://github.com/Yggdroot/indentLine/issues/154#issuecomment-214586122), you say that there is a conflict with that plugin. If you have time, would you please explain a little bit what the conflict is? Thank you very much!!
