### ISSUE TITLE
Conflict with NERDTreeToggle when leading space is enabled.

### ISSUE THREAD

**Issue by nicketech** [Yggdroot/indentLine#335]
<p>When g:indentLine_leadingSpaceEnabled is set to 0 (by default), NERDTreeToggle works perfectly</p>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/7jKkYXt/Screenshot-from-2020-12-01-22-52-15.png" alt="Screenshot-from-2020-12-01-22-52-15" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/sbTmqcy/Screenshot-from-2020-12-01-22-52-40.png" alt="Screenshot-from-2020-12-01-22-52-40" border="0"></a>
</br>
</br>
<p>But when g:indentLine_leadingSpaceEnabled is set to 1, NERDTreeToggle don't show the indentation at all</p>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/0hqhBX1/Screenshot-from-2020-12-01-22-53-36.png" alt="Screenshot-from-2020-12-01-22-53-36" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/gykWRcW/Screenshot-from-2020-12-01-22-53-13.png" alt="Screenshot-from-2020-12-01-22-53-13" border="0"></a>

**Comment by Yggdroot** [comment]
`autocmd FileType nerdtree setlocal conceallevel=2`

**Comment by nicketech** [comment]
It works!
