### ISSUE TITLE
g:indentLine_defaultGroup doesn't seem to take effect

### ISSUE THREAD

**Issue by zuqini** [Yggdroot/indentLine#339]
Terminal: Iterm2 Build 3.4.3

From `init.vim`:
```
let g:indentLine_defaultGroup = 'Constant'
```
From `theme.vim`: 
```
call s:HL('Constant', s:palette.orange, s:palette.none) " s.palette.orange is #FF9E64
```

Observed:
Even though the highlight group is set to 'Constant' which is working elsewhere in the code, the indentline colors remain unchanged.
![image](https://user-images.githubusercontent.com/5790854/103167880-d57fc180-47e3-11eb-8ae8-e9f640613a25.png)
Expected:
![image](https://user-images.githubusercontent.com/5790854/103167915-0b24aa80-47e4-11eb-940d-11179cb5ae1c.png)

From reading the docs, I believe everything is configured properly. Please let me know if I'm missing anything. Thank you.

**Comment by Yggdroot** [comment]
I think `call s:HL('Constant', s:palette.orange, s:palette.none) " s.palette.orange is #FF9E64`  is executed after indentLine knows the color of Constant.

Use a normal colorscheme, It should work as expected.

**Comment by zuqini** [comment]
I see. Using one of Vim's built in color scheme like the following works:
```
colorscheme blue
let g:indentLine_defaultGroup = 'Constant'
```

I suppose this means that this setting will not work with custom themes from `/colors/`. I'm wondering if it makes sense to use the autocmd to support setting the indentLine color after all the themes are loaded in the future (or if there's other solutions to support this case).

If not, feel free to close this issue

**Comment by Yggdroot** [comment]
> I suppose this means that this setting will not work with custom themes from /colors/. 

No, it will work for all colorschemes from /colors/. This issue is caused by how your colorscheme is implemented.

**Comment by zuqini** [comment]
Got it. Thanks, will close this issue here.
