### ISSUE TITLE
indentLine_setColors can't work with vim-plug's lazy load

### ISSUE THREAD

**Issue by fcying** [Yggdroot/indentLine#345]
if I use lazy load  `Plug 'Yggdroot/indentLine' , {'on':'IndentLinesToggle'}`
indentLine_setColors can't work, 
![image](https://user-images.githubusercontent.com/106934/105441202-01874900-5ca3-11eb-9389-680d74f1f560.png)

not use lazy load it work well
`Plug 'Yggdroot/indentLine'`
![image](https://user-images.githubusercontent.com/106934/105441257-1ebc1780-5ca3-11eb-9c67-3325c0678dd9.png)

**Comment by ppwwyyxx** [comment]
Having the same issue.
It seems this is because `indentLine` uses `autocmd BufRead` to initialize the colors. So on lazy load it does not initialize the colors.
Would be great to keep this issue open.
