### ISSUE TITLE
The lines doesn't appear for two characters indentation, only for 4 characters and so on

### ISSUE THREAD

**Issue by hrqmonteiro** [Yggdroot/indentLine#348]
![2021-02-07_12-24](https://user-images.githubusercontent.com/17055027/107151078-a28b2a80-6958-11eb-855c-c409e50a1037.png)

I have `set tabstop=2`, `set shiftwidth=2`, `set expandtab` and `set smarttab` activated. 
Why does the plugin don't show the indentlines at two spaces, only at four spaces?

**Comment by Yggdroot** [comment]
doesn't the picture show the expected behavior?

**Comment by MaMrEzO** [comment]
Expected behavior:
![Screenshot_20210318_152256](https://user-images.githubusercontent.com/1070230/111622025-f1e93400-87fd-11eb-8951-69e0a51fc799.png)

And unexpected one with 2 spcs:
![Screenshot_20210318_152527](https://user-images.githubusercontent.com/1070230/111622241-2ceb6780-87fe-11eb-82d9-7a802dba7134.png)

with 4 spcs:
![Screenshot_20210318_152629](https://user-images.githubusercontent.com/1070230/111622364-54423480-87fe-11eb-9d8d-ba50a4141e3f.png)

Dart code formatter uses 3 spcs!!!!:
**This is too bad!** 
![Screenshot_20210318_152739](https://user-images.githubusercontent.com/1070230/111622532-8c497780-87fe-11eb-84ce-9c7fc96e49f8.png)

**Comment by Yggdroot** [comment]
> Expected behavior:
> ![Screenshot_20210318_152256](https://user-images.githubusercontent.com/1070230/111622025-f1e93400-87fd-11eb-8951-69e0a51fc799.png)
> 
> And unexpected one with 2 spcs:
> ![Screenshot_20210318_152527](https://user-images.githubusercontent.com/1070230/111622241-2ceb6780-87fe-11eb-82d9-7a802dba7134.png)
> 
> with 4 spcs:
> ![Screenshot_20210318_152629](https://user-images.githubusercontent.com/1070230/111622364-54423480-87fe-11eb-9d8d-ba50a4141e3f.png)
> 
> Dart code formatter uses 3 spcs!!!!:
> **This is too bad!**
> ![Screenshot_20210318_152739](https://user-images.githubusercontent.com/1070230/111622532-8c497780-87fe-11eb-84ce-9c7fc96e49f8.png)

this is because your vim setting &sw is 4. 
https://github.com/Yggdroot/indentLine/blob/5617a1cf7d315e6e6f84d825c85e3b669d220bfa/doc/indentLine.txt#L172-176

**Comment by hrqmonteiro** [comment]
> Expected behavior:
> ![Screenshot_20210318_152256](https://user-images.githubusercontent.com/1070230/111622025-f1e93400-87fd-11eb-8951-69e0a51fc799.png)
> 
> And unexpected one with 2 spcs:
> ![Screenshot_20210318_152527](https://user-images.githubusercontent.com/1070230/111622241-2ceb6780-87fe-11eb-82d9-7a802dba7134.png)
> 
> with 4 spcs:
> ![Screenshot_20210318_152629](https://user-images.githubusercontent.com/1070230/111622364-54423480-87fe-11eb-9d8d-ba50a4141e3f.png)
> 
> Dart code formatter uses 3 spcs!!!!:
> **This is too bad!**
> ![Screenshot_20210318_152739](https://user-images.githubusercontent.com/1070230/111622532-8c497780-87fe-11eb-84ce-9c7fc96e49f8.png)

That is exactly my point. And my shiftwidth is set to 2, and it still doesn't show the expected behaviour.

**Comment by hrqmonteiro** [comment]
> > Expected behavior:
> > ![Screenshot_20210318_152256](https://user-images.githubusercontent.com/1070230/111622025-f1e93400-87fd-11eb-8951-69e0a51fc799.png)
> > And unexpected one with 2 spcs:
> > ![Screenshot_20210318_152527](https://user-images.githubusercontent.com/1070230/111622241-2ceb6780-87fe-11eb-82d9-7a802dba7134.png)
> > with 4 spcs:
> > ![Screenshot_20210318_152629](https://user-images.githubusercontent.com/1070230/111622364-54423480-87fe-11eb-9d8d-ba50a4141e3f.png)
> > Dart code formatter uses 3 spcs!!!!:
> > **This is too bad!**
> > ![Screenshot_20210318_152739](https://user-images.githubusercontent.com/1070230/111622532-8c497780-87fe-11eb-84ce-9c7fc96e49f8.png)
> 
> this is because your vim setting &sw is 4.
> 
> https://github.com/Yggdroot/indentLine/blob/5617a1cf7d315e6e6f84d825c85e3b669d220bfa/doc/indentLine.txt#L172-L176

Still doesn't work for me. Indentlines only show for 4 spaces and so on.
