### ISSUE TITLE
How to disable for terminal buffer?

### ISSUE THREAD

**Issue by bew** [Yggdroot/indentLine#351]
Hello, I'm using neovim's terminal buffers, and the indentlines are shown when they shouldn't (this is not code!)

Try with:
```
<open nvim>
:vsplit term://sh
i         (to enter in terminal mode, then run the following command:)
echo "                            see the indentation before?"
```
![image](https://user-images.githubusercontent.com/9730330/110452825-d4adba80-80c5-11eb-9407-139c2ccf3711.png)

I would like to disable the indentation lines you see here

**Comment by Yggdroot** [comment]
Please refer to #206 .

**Comment by bew** [comment]
That would work, I failed at searching existing issues it seems, sorry for the noise!
