### ISSUE TITLE
First indent level not showing line

### ISSUE THREAD

**Issue by ChrisMcDearman** [Yggdroot/indentLine#356]
The indent line only starts at the second level.
![Screenshot from 2021-05-13 19-18-14](https://user-images.githubusercontent.com/26758180/118199016-1b9a9200-b420-11eb-87cb-779317254c62.png)

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/indentLine/blob/5617a1cf7d315e6e6f84d825c85e3b669d220bfa/doc/indentLine.txt#L83-L88
