### ISSUE TITLE
First indent line character is different from the rest

### ISSUE THREAD

**Issue by felipejoribeiro** [Yggdroot/indentLine#360]
Here is an example of the problem:

![image](https://user-images.githubusercontent.com/39244876/128511226-474ae06b-ebc4-48d8-8fae-e086d6dd6a86.png)

The config for the plugin follows ahead:

```
let g:indentLine_char = '┊'
let g:indentLine_showFirstIndentLevel = 1
```

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/indentLine/blob/5617a1cf7d315e6e6f84d825c85e3b669d220bfa/doc/indentLine.txt#L43-L48

**Comment by felipejoribeiro** [comment]
Perfect! Thank you very much.
Sorry for not finding this myself.
