### ISSUE TITLE
eat quotation marks?

### ISSUE THREAD

**Issue by Martinits** [Yggdroot/indentLine#368]
My vimrc is here: https://github.com/Martinits/dotfiles/blob/master/.vim/vimrc
When I edit some json files, the quotation marks disappear (just on the screen, not in the file).
Then the quotation marks come back when I comment out this plugin in vimrc.
I'm not sure whether it's this plugin's fault, but commenting out other plugins have no such effect.
![image](https://user-images.githubusercontent.com/48900241/156313974-210c5ee3-1e67-4c1a-92cb-e0b11aa6e041.png)
![image](https://user-images.githubusercontent.com/48900241/156314030-5af38ec6-fdb7-45e1-a509-16584ab886a1.png)

**Comment by Yggdroot** [comment]
let g:vim_json_conceal=0

**Comment by Martinits** [comment]
Oh thanks a lot.
Need to learn more about vim.
