### ISSUE TITLE
error dected when vim startup

### ISSUE THREAD

**Issue by ljhui** [Yggdroot/indentLine#369]
I use vim-bootstrap to generate my vim config with some modifies, it works well in the past time, but recently vim throw out a error everytime when startup:
```
Error detected while processing BufWinEnter Autocommands for "*"..function <SNR>99_Setup[6]..<SNR>99_IndentLinesEnable[10]..<SNR>99_SetConcealOption:        
line    8:
```
this is[ my vimrc file](https://gist.github.com/ljhui/119df3dfcfd6a95d9bc2facc55b54f44), I have used `:PlugUpdate` update to latest indentLine  version, the error still there. Temporarily, I have to comment `Plug 'Yggdroot/indentLine'` to let those errors disappear. I doesn't play well with vim,  how to fix it?

**Comment by davised** [comment]
I'm having the same issue, just started recently.

```
vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 09 2022 00:00:00)
Included patches: 1-4529
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
```

I'm on fedora workstation version 35 if that matters.

**Comment by ljhui** [comment]
> I'm having the same issue, just started recently.
> 
> ```
> vim --version
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 09 2022 00:00:00)
> Included patches: 1-4529
> Modified by <bugzilla@redhat.com>
> Compiled by <bugzilla@redhat.com>
> ```
> 
> I'm on fedora workstation version 35 if that matters.

same with you, my system is also fedora 35, the vim version actually is  same

**Comment by starit** [comment]
same here, latest macbook pro (with m1 max chip)

**Comment by prandelicious** [comment]
Experiencing the same error here. Is there an alternative to this plugin?

**Comment by mopig** [comment]
Same error.

**Comment by ljhui** [comment]
in my fedora 35, I just use `sudo dnf downgrade vim-enhanced --allowerasing` to downgrade vim to 8.2.3404, after that, the error goes, so threre is some problem with indentLine compatibling with newer vim.

**Comment by bignimbus** [comment]
I have [this same line](https://gist.github.com/ljhui/119df3dfcfd6a95d9bc2facc55b54f44#file-vimrc-L182) in my `vimrc`.  After inspecting this snippet in the source code:

https://github.com/Yggdroot/indentLine/blob/7753505f3c500ec88d11e9373d05250f49c1d900/after/plugin/indentLine.vim#L104

I tried changing `0` to `"inc"` in my `vimrc`.  That appears to have resolved the issue.  So try changing this:

```vim
" :(
let g:indentLine_concealcursor = 0
```

to this:

```vim
" :)
let g:indentLine_concealcursor = "inc"
```

**Comment by Yggdroot** [comment]
https://gist.github.com/ljhui/119df3dfcfd6a95d9bc2facc55b54f44#file-vimrc-L182

Why do you set `let g:indentLine_concealcursor = 0`? `g:indentLine_concealcursor` is a string, you can set `let g:indentLine_concealcursor = ''` or leave it alone.

**Comment by ljhui** [comment]
> https://gist.github.com/ljhui/119df3dfcfd6a95d9bc2facc55b54f44#file-vimrc-L182
> 
> Why do you set `let g:indentLine_concealcursor = 0`? `g:indentLine_concealcursor` is a string, you can set `let g:indentLine_concealcursor = ''` or leave it alone.

this is auto-generated  by vim-bootstrap ，all vim-bootstrap generated config files have this line, maybe vim-bootstrap still uses an out-dated  customization . I should read the IndentLine readme first, actually this line cause the problem, after change , the error fixs, thanks all!
