### ISSUE TITLE
neovim use

### ISSUE THREAD

**Issue by xuyastc** [Yggdroot/indentLine#379]
Hi, Can I use on neovim? I tried. But it's didn't work, please help me,thanks
<img width="330" alt="Snipaste_2022-11-04_11-49-10" src="https://user-images.githubusercontent.com/37319368/199881536-77b5a34f-81f9-42c9-874e-4f9db0bdbb2e.png">

**Comment by Yggdroot** [comment]
Yes, it can work on both vim and neovim.

**Comment by xuyastc** [comment]
I'm sorry. it's work. I didn't show it because I didn't have enough levels before
