### ISSUE TITLE
Is there any option to make the sign '|' not copied

### ISSUE THREAD

**Issue by wklken** [Yggdroot/indentLine#45]
hi, I got a problem, when I use mouse select and copy the code in the terminal, and paste to another file, the indent sign '|'  was copied & pasted too.(use yy&p is fine)
I wander if it is possible to avoid that.
thx

**Comment by varac** [comment]
I'm having the same problem, the lines are nice, but when you try to copy&paste, the line symbol is included leading to messed up code when pasted.
I though about using a whitespace that could be colored, but I can't make this happen. Any hints ?

**Comment by varac** [comment]
ugh, https://github.com/nathanaelkane/vim-indent-guides is the plugin that works for me regarding brute copy&paste
