### ISSUE TITLE
let g:indentLine_fileTypeExclude = ['nerdtree'] seems doesn't work

### ISSUE THREAD

**Issue by kikyous** [Yggdroot/indentLine#47]
I have `let g:indentLine_fileTypeExclude = ['nerdtree']` in my vimrc.
but it seems doesn't work.

**Comment by m47h4r** [comment]
> autocmd FileType help,nerdtree IndentLinesToggle
> 
> seems to work.

That causes nerdtree to be having indentlines every other time when you open or close it, I just used the disable command instead:

`autocmd FileType help,nerdtree IndentLinesDisable`

**Comment by diegoulloao** [comment]
> > autocmd FileType help,nerdtree IndentLinesToggle
> > seems to work.
> 
> That causes nerdtree to be having indentlines every other time when you open or close it, I just used the disable command instead:
> 
> `autocmd FileType help,nerdtree IndentLinesDisable`

this works 👍🏻
