### ISSUE TITLE
syntax broken in .css.scss file

### ISSUE THREAD

**Issue by njia** [Yggdroot/indentLine#64]
Have not tried other file yet, all default setting for indentLine and it broken .css.scss file syntax highligh

with indentLine
![screen shot 2013-12-11 at 10 28 52 am](https://f.cloud.github.com/assets/5069474/1719814/dca39fb0-61f2-11e3-9ee4-69345dab788e.png)

Manually removed indentLine char
![screen shot 2013-12-11 at 10 29 18 am](https://f.cloud.github.com/assets/5069474/1719825/008aa54a-61f3-11e3-9e76-42bc5d547309.png)

More screen capture
![screen shot 2013-12-11 at 11 08 44 am](https://f.cloud.github.com/assets/5069474/1720106/72311c88-61f8-11e3-9212-be58e9cf225c.png)

**Comment by Yggdroot** [comment]
fixed by fixing issue #91
