### ISSUE TITLE
Broken slim and haml syntax

### ISSUE THREAD

**Issue by alexbel** [Yggdroot/indentLine#73]
Removing line `exec 'syn match IndentLine /\%(^\)\@! \{'.(space-1).'}\zs / containedin=ALL contained conceal cchar=' . g:indentLine_char` in this https://github.com/Yggdroot/indentLine/commit/e31f896a2cd637aad95d87215bb8e8cd59f029ec commit breaks slim and haml syntax.
Maybe it breaks syntax highlighting for other types as well, I didn't heck.

**Comment by nguyenj** [comment]
@alexbel I see that it if fixed; however, my syntax highlighting is still not correct for haml.

**Comment by nguyenj** [comment]
@alexbel actually, your fixed worked; however the updated on master is not working.
