### ISSUE TITLE
Indent lines disappear if I do ":e" to reload the current file

### ISSUE THREAD

**Issue by jduan** [Yggdroot/indentLine#77]
I'm using vim 7.4.52 and the latest version of this plugin. Can you help?

**Comment by exAspArk** [comment]
Hi,

Similar issue happens when I run `:so $MYVIMRC | edit!`. After that indentLine stops working.  NeoVim 0.1.7 + the latest version of the plugin

**Comment by ErikReider** [comment]
I'm still experiencing this issue today. Has anyone solved this yet?
