### ISSUE TITLE
Issue with YAML syntax highlightinh

### ISSUE THREAD

**Issue by kballenegger** [Yggdroot/indentLine#91]
I've found that the plugin will break regular syntax highlighting on certain files. I've seen this happen on a YAML file. Lines where the indent guides appeared would lose their syntax highlighting.

**Comment by takac** [comment]
:+1: Broken for me too

**Comment by newvar** [comment]
broken for LESS (genoma/vim-less), seems that works for CSS (JulesWang/css.vim)

**Comment by Yggdroot** [comment]
fixed

**Comment by adoyle-h** [comment]
The SASS and YAML syntax highlighting are not the duties of indentLine plugin. The fix may confuse user who use another SASS and YAML vim plugins. @Yggdroot

**Comment by Yggdroot** [comment]
@adoyle-h I know, but too many people complain about it.
