### ISSUE TITLE
i can't see any indentlines

### ISSUE THREAD

**Issue by Vienzzion** [Yggdroot/indentLine#99]
i can't see any indent lines i'm on linuxmint using terminal vim 7.4
default install try changing the colors and using | : as indent characters but its not showing up

**Comment by kennykaye** [comment]
I've been experiencing this issue intermittently, even after recompiling Vim and removing all other configuration in attempt to isolate a conflict.  The only thing that has worked has been enabling indentLine manually:

```vim
autocmd BufRead * :IndentLinesEnable
```

**Comment by Yggdroot** [comment]
Similar with issue #59
